/* NetworkBook 용어 데이터 — [한국어, 영어, 설명, 장 slug]
   용어집(glossary.html)과 본문 용어 툴팁(common.js)이 함께 쓴다. */
window.NB_TERMS = [
    // 01 intro
    ["교환기", "Switchboard / Exchange", "여러 회선 중 원하는 두 개를 그때그때 이어 주는 장치. 모두를 직접 잇지 않아도 되게 해 주며, 오늘날 스위치와 라우터의 조상이다.", "intro"],
    ["메트칼프의 법칙", "Metcalfe's law", "네트워크의 가치가 연결된 사용자 수의 제곱에 비례한다는 경험칙. 연결 가능한 쌍의 수 n(n−1)/2에서 나왔다.", "intro"],
    ["노드", "Node", "네트워크에서 데이터를 보내거나 받거나 넘겨주는 지점. 휴대폰, 서버, 스위치, 라우터가 모두 노드다.", "intro"],
    ["링크", "Link", "두 노드를 잇는 통로. 구리선, 광섬유, 전파가 모두 링크가 될 수 있다.", "intro"],
    ["토폴로지", "Topology", "노드와 링크를 어떤 모양으로 배치했는지를 나타내는 연결 형태. 버스·링·스타·트리·메시가 기본형이다.", "intro"],
    ["호스트", "Host", "데이터를 처음 만들거나 마지막에 받는 끝 장치. 휴대폰, 노트북, 서버 등.", "intro"],
    ["접속망", "Access network", "가정·사무실에서 통신사 건물(국사)이나 기지국까지의 마지막 구간 망. 광 FTTH, DSL, 케이블, 이동통신 등이 있다.", "intro"],
    ["ISP", "Internet Service Provider", "인터넷 접속을 제공하는 통신사. 자기 접속망과 백본을 운영하고 다른 망과 연결한다.", "intro"],
    ["백본", "Backbone", "도시와 도시, 나라와 나라를 잇는 고속 중심망. 대용량 라우터와 광 전송 장비로 이뤄진다.", "intro"],
    ["IXP", "Internet Exchange Point", "여러 통신사·콘텐츠 회사의 망이 한곳에 모여 트래픽을 직접 맞교환하는 시설. 우회 경로를 줄여 지연과 비용을 낮춘다.", "intro"],
    ["대역폭", "Bandwidth", "1초에 보낼 수 있는 데이터의 양(bps). 신호 분야에서는 신호가 차지하는 주파수 폭(Hz)을 뜻하기도 한다.", "intro"],
    ["지연", "Latency", "데이터가 출발해서 도착할 때까지 걸리는 시간. 거리(전파 지연), 전송, 처리, 대기 시간이 더해진다.", "intro"],
    ["왕복 시간", "RTT (Round-Trip Time)", "요청을 보내고 응답이 돌아올 때까지 걸리는 시간. ping이 재는 값이다.", "intro"],
    ["처리량", "Throughput", "실제로 1초에 전달된 쓸모 있는 데이터의 양. 헤더, 재전송, 지연 때문에 대역폭보다 작다.", "intro"],
    ["스니커넷", "Sneakernet", "저장장치를 사람이나 트럭이 직접 나르는 데이터 전송. 지연은 크지만 대량 데이터에서는 대역폭이 매우 크다.", "intro"],
    // 02 signal
    ["아날로그 신호", "Analog signal", "연속적인 아무 값이나 가질 수 있는 신호. 목소리를 그대로 닮은 옛 전화 전압이 예다. 증폭할 때 잡음도 함께 커져 누적된다.", "signal"],
    ["디지털 신호", "Digital signal", "정해진 몇 개의 값(레벨)만 쓰는 신호. 받는 쪽이 가장 가까운 값으로 판정하므로 잡음에 강하다.", "signal"],
    ["재생 중계", "Regeneration", "중계기가 받은 신호를 0과 1로 판정한 뒤 깨끗한 신호를 새로 만들어 보내는 것. 판정이 맞는 한 잡음이 쌓이지 않는다.", "signal"],
    ["주파수", "Frequency", "1초에 몇 번 반복하는지를 나타내는 값. 단위는 Hz이며 주기의 역수다.", "signal"],
    ["위상", "Phase", "주기적인 파동이 한 주기 안에서 어디쯤에 있는지를 0~360°로 나타낸 값. 180° 어긋난 두 파동은 서로 상쇄된다.", "signal"],
    ["파장", "Wavelength", "파동이 한 주기 동안 나아가는 거리. 속도 ÷ 주파수. 2.4 GHz 전파의 파장은 약 12.5 cm다.", "signal"],
    ["고조파", "Harmonics", "기본 주파수의 정수 배인 주파수 성분. 네모파는 홀수 배 고조파들의 합으로 만들어진다(푸리에 급수).", "signal"],
    ["보", "Baud (symbol rate)", "1초에 보내는 심볼(신호 단위)의 수. 심볼 하나에 여러 비트를 실으면 비트율이 보보다 커진다.", "signal"],
    ["나이퀴스트 공식", "Nyquist formula", "잡음이 없는 대역폭 B 채널의 최대 비트율 2B·log₂M. M은 심볼이 가질 수 있는 레벨 수다.", "signal"],
    ["잡음", "Noise", "신호에 섞여 드는 원치 않는 무작위 요동. 상온 열잡음은 1 Hz당 약 −174 dBm이다.", "signal"],
    ["신호 대 잡음비", "SNR (Signal-to-Noise Ratio)", "신호 전력을 잡음 전력으로 나눈 값. 보통 dB로 나타내며 통신 속도의 한계를 정한다.", "signal"],
    ["데시벨", "Decibel (dB)", "두 전력의 비를 10·log₁₀로 나타낸 로그 단위. +3 dB ≈ 2배, +10 dB = 10배, 손실 계산이 덧셈·뺄셈이 된다.", "signal"],
    ["dBm", "dB-milliwatt", "1 mW를 기준으로 한 전력의 데시벨 표현. 0 dBm = 1 mW, 30 dBm = 1 W, −90 dBm = 1 pW.", "signal"],
    ["섀넌 용량", "Shannon capacity", "잡음이 있는 채널로 오류 없이 보낼 수 있는 최대 속도 C = B·log₂(1+SNR). 대역폭에 비례하고 SNR에는 로그로 는다.", "signal"],
    ["비트 오류율", "BER (Bit Error Rate)", "받은 비트 중 틀린 비트의 비율. 광 링크는 오류 정정 후 10⁻¹² 이하를 목표로 한다.", "signal"],
    ["패리티", "Parity", "1의 개수가 짝수(또는 홀수)가 되도록 덧붙이는 검사 비트. 1비트 오류를 찾아낸다.", "signal"],
    ["CRC", "Cyclic Redundancy Check", "데이터를 다항식으로 나눈 나머지를 붙여 오류를 검출하는 방식. 이더넷 프레임 끝의 32비트 검사값이 대표적이다.", "signal"],
    ["FEC", "Forward Error Correction", "받는 쪽이 재전송 없이 스스로 오류를 고칠 수 있도록 여분 비트를 넣는 순방향 오류 정정. LDPC·RS·폴라 부호 등.", "signal"],
    ["해밍 코드", "Hamming code", "데이터 4비트에 패리티 3비트를 붙여 1비트 오류의 위치를 찾아 고치는 고전적인 오류 정정 부호.", "signal"],
    ["다중화", "Multiplexing", "하나의 매체를 시간·주파수·코드·파장 등으로 나눠 여러 신호가 함께 쓰게 하는 것(TDM·FDM·CDM·WDM).", "signal"],
    // 03 layers
    ["프로토콜", "Protocol", "통신하는 양쪽이 지키기로 한 약속. 메시지의 형식, 주고받는 순서, 오류가 났을 때의 행동을 정한다.", "layers"],
    ["헤더", "Header", "데이터 앞에 붙는 머리말. 택배 송장처럼 정해진 자리에 주소, 번호, 길이 같은 제어 정보를 적는다.", "layers"],
    ["트레일러", "Trailer", "데이터 뒤에 붙는 꼬리말. 이더넷 프레임 끝의 오류 검사값(FCS)이 대표적이다.", "layers"],
    ["계층", "Layer", "통신의 일을 나눈 단계. 각 계층은 바로 아래 계층의 서비스만 믿고 자기 문제 하나를 푼다.", "layers"],
    ["모래시계 모델", "Hourglass model", "위(응용)와 아래(매체)는 다양하지만 가운데 허리(IP)는 하나뿐인 인터넷 구조를 모래시계에 빗댄 말.", "layers"],
    ["OSI 7계층", "OSI reference model", "ISO가 1984년에 정리한 7단계 통신 모델(물리·데이터 링크·네트워크·전송·세션·표현·응용). L2, L4 같은 계층 번호의 출처.", "layers"],
    ["TCP/IP 모델", "Internet protocol suite", "실제 인터넷이 쓰는 4계층(응용·전송·인터넷·링크) 모델. 링크를 물리와 나눠 5계층으로 설명하기도 한다.", "layers"],
    ["세그먼트", "Segment", "TCP 계층의 데이터 단위. TCP 헤더와 그 안의 응용 데이터를 합한 덩어리. UDP의 단위는 데이터그램이라 부른다.", "layers"],
    ["캡슐화", "Encapsulation", "데이터가 아래 계층으로 내려가며 계층마다 헤더(와 트레일러)를 덧씌우는 과정. 받는 쪽은 역순으로 벗긴다.", "layers"],
    ["페이로드", "Payload", "어떤 계층 입장에서 헤더를 뺀 실제 내용물. 위 계층의 헤더와 데이터 전체가 아래 계층의 페이로드가 된다.", "layers"],
    ["오버헤드", "Overhead", "실제 데이터가 아닌데 함께 전송되는 헤더·패딩·동기 신호 같은 부가 바이트, 또는 그 비율.", "layers"],
    ["FCS", "Frame Check Sequence", "이더넷 프레임 끝의 4바이트 CRC 값. 받는 쪽이 다시 계산해 맞지 않으면 프레임을 버린다.", "layers"],
    ["TTL", "Time To Live", "IP 헤더의 남은 수명 값. 라우터를 하나 지날 때마다 1씩 줄고 0이 되면 패킷을 버려 무한 순환을 막는다.", "layers"],
    ["체크섬", "Checksum", "데이터를 정해진 방식으로 더해 만든 검사값. IP·TCP·UDP 헤더에 있어 손상된 패킷을 걸러낸다.", "layers"],
    ["표준", "Standard", "여러 회사의 장비가 서로 통하도록 문서로 정한 공통 약속. IETF, IEEE, 3GPP, ITU 등이 만든다.", "layers"],
    ["RFC", "Request for Comments", "IETF가 발행하는 인터넷 표준·정보 문서 시리즈. 번호가 붙으면 고치지 않고 새 RFC로 대체한다.", "layers"],
    ["종단 간 원칙", "End-to-end principle", "신뢰성·암호화 같은 기능은 양 끝 컴퓨터에 두고 망 중간은 단순하게 유지하자는 인터넷 설계 원칙.", "layers"],
    ["미들박스", "Middlebox", "NAT, 방화벽, 프록시처럼 패킷을 단순히 나르는 것을 넘어 들여다보거나 고쳐 쓰는 중간 장비.", "layers"],
    // 04 copper
    ["꼬임쌍선", "Twisted pair", "두 가닥 구리선을 서로 꼬아 만든 선. 차동 신호와 함께 쓰여 외부 잡음을 상쇄한다. 랜선과 전화선의 기본 구조.", "copper"],
    ["차동 신호", "Differential signaling", "한 쌍의 선에 서로 반대 전압(+V/−V)을 싣고 받는 쪽에서 두 선의 차이만 읽는 방식. 두 선에 똑같이 실린 잡음은 지워진다.", "copper"],
    ["공통 모드 잡음", "Common-mode noise", "차동 쌍의 두 선에 같은 크기·같은 부호로 실리는 잡음. 차동 수신기가 두 선을 빼면 사라진다.", "copper"],
    ["동축 케이블", "Coaxial cable", "가운데 심선을 절연체와 원통형 금속 차폐가 감싼 케이블. 차폐 덕분에 높은 주파수까지 잡음 없이 보낸다. 케이블 TV·안테나선.", "copper"],
    ["UTP", "Unshielded Twisted Pair", "차폐 없는 꼬임쌍선 4쌍으로 된 랜선. Cat5e·6·6A 등 카테고리로 성능 등급을 나눈다.", "copper"],
    ["감쇠", "Attenuation", "신호가 매체를 지나며 약해지는 정도. 구리선에서는 거리에 비례하고 주파수가 높을수록 커진다. 보통 dB/100 m로 나타낸다.", "copper"],
    ["표피 효과", "Skin effect", "주파수가 높을수록 교류 전류가 도체 겉면으로만 흐르는 현상. 실효 저항이 커져 고주파 감쇠가 늘어난다.", "copper"],
    ["누화", "Crosstalk", "옆 선의 신호가 전자기적으로 새어 드는 잡음. 송신 쪽에서 생기는 NEXT와 먼 끝에서 생기는 FEXT가 있다.", "copper"],
    ["NRZ", "Non-Return-to-Zero", "1은 높은 전압, 0은 낮은 전압을 비트 시간 동안 유지하는 가장 단순한 라인 코딩. 같은 비트가 이어지면 전이가 없다.", "copper"],
    ["라인 코딩", "Line coding", "비트열을 선에 싣기 좋은 전압 모양으로 바꾸는 규칙. 직류 균형, 클럭 복원, 대역폭 절약을 위해 쓴다.", "copper"],
    ["맨체스터 부호", "Manchester code", "비트마다 가운데에서 반드시 전압이 뒤집히는 라인 코딩. 클럭 복원이 쉽고 직류가 없지만 대역폭을 두 배 쓴다. 10BASE-T에 쓰였다.", "copper"],
    ["8b/10b", "8b/10b encoding", "8비트를 10비트 부호로 바꿔 직류 균형과 충분한 전이를 보장하는 부호화. 20%의 오버헤드가 있다.", "copper"],
    ["눈 모양 그림", "Eye diagram", "무작위 비트 파형을 비트 두 개 길이로 잘라 겹쳐 그린 그림. 가운데 열린 ‘눈’의 높이와 폭이 신호 품질을 보여 준다.", "copper"],
    ["에코 제거", "Echo cancellation", "한 선으로 동시에 주고받을 때 자기 송신 신호가 수신기로 새어 든 성분을 계산해 빼는 디지털 신호 처리 기법.", "copper"],
    ["PoE", "Power over Ethernet", "랜선으로 데이터와 함께 직류 전력(약 44~57 V)을 보내는 표준. 802.3bt는 최대 90 W까지 공급한다.", "copper"],
    ["가입자 회선", "Last mile", "통신사 건물에서 각 가정·사무실까지의 마지막 구간. 망에서 가장 많고 바꾸기 비싼 부분.", "copper"],
    ["DSL", "Digital Subscriber Line", "전화선의 목소리 대역 위 높은 주파수를 데이터에 쓰는 가입자망 기술. ADSL, VDSL, G.fast 등이 있고 거리에 민감하다.", "copper"],
    ["DOCSIS", "Data Over Cable Service Interface Specification", "케이블 TV용 동축망으로 인터넷을 제공하는 케이블 모뎀 표준. 동네 가구들이 대역을 공유한다.", "copper"],
    ["특성 임피던스", "Characteristic impedance", "전송선로를 따라 흐르는 파동이 느끼는 고유 임피던스. UTP 쌍 100 Ω, 방송용 동축 75 Ω, 무선 장비 동축 50 Ω.", "copper"],
    ["임피던스 정합", "Impedance matching", "선로 끝이나 연결부의 임피던스를 선로와 같게 맞춰 신호 반사를 없애는 것.", "copper"],
    // 05 optical
    ["코어", "Core", "광섬유 한가운데에서 빛이 지나가는 유리 부분. 클래딩보다 굴절률이 조금 높고, 단일 모드는 지름 약 9 µm, 다중 모드는 50~62.5 µm다.", "optical"],
    ["클래딩", "Cladding", "코어를 감싸는 굴절률이 조금 낮은 유리층(지름 125 µm). 경계에서 전반사가 일어나 빛을 코어 안에 가둔다.", "optical"],
    ["굴절률", "Refractive index", "빛이 그 물질 속에서 진공보다 몇 배 느려지는지를 나타내는 값. 석영 유리는 약 1.47이라 빛이 1 km를 약 5 µs에 간다.", "optical"],
    ["임계각", "Critical angle", "굴절률이 높은 곳에서 낮은 곳으로 갈 때 굴절각이 90°가 되는 입사각. θc = arcsin(n₂/n₁)이며 이보다 비스듬하면 전반사가 일어난다.", "optical"],
    ["전반사", "Total internal reflection", "빛이 임계각보다 비스듬히 경계에 닿아 손실 없이 100% 되튕기는 현상. 광섬유가 빛을 가두는 원리다.", "optical"],
    ["모드", "Mode", "광섬유 안에서 빛이 갈 수 있는 하나하나의 길(전자기장 분포). 코어가 굵으면 여러 모드가 동시에 존재한다.", "optical"],
    ["다중 모드 광섬유", "Multimode fiber (MMF)", "코어가 굵어(50~62.5 µm) 여러 모드가 함께 지나가는 광섬유. 싸고 연결이 쉽지만 모드 분산 때문에 수백 m 이내에 쓴다.", "optical"],
    ["단일 모드 광섬유", "Single-mode fiber (SMF)", "코어를 약 9 µm로 가늘게 해 모드를 하나만 남긴 광섬유. 모드 분산이 없어 장거리 통신망과 해저 케이블에 쓴다.", "optical"],
    ["모드 분산", "Modal dispersion", "모드마다 이동 경로의 길이가 달라 같은 펄스가 도착할 때 시간적으로 퍼지는 현상. 다중 모드 광섬유의 속도·거리를 제한한다.", "optical"],
    ["색 분산", "Chromatic dispersion", "유리 속에서 파장마다 빛의 속도가 달라 펄스가 퍼지는 현상. 표준 단일 모드 광섬유는 1550 nm에서 약 17 ps/(nm·km)다.", "optical"],
    ["광 링크 예산", "Optical link budget", "송신 출력에서 광섬유·커넥터·접속 손실을 뺀 수신 전력이 수신 감도보다 여유 있게 큰지 따지는 계산.", "optical"],
    ["EDFA", "Erbium-Doped Fiber Amplifier", "어븀을 섞은 광섬유에 펌프 레이저를 쏘아 1530~1565 nm 빛을 전기 변환 없이 증폭하는 광증폭기. WDM 채널 전체를 한꺼번에 키운다.", "optical"],
    ["파장 분할 다중화", "WDM (Wavelength Division Multiplexing)", "서로 다른 파장(색)의 빛 여러 개를 한 광섬유에 함께 실어 보내는 기술. 각 파장이 독립된 채널이 된다.", "optical"],
    ["DWDM", "Dense WDM", "ITU 격자에 맞춰 50~100 GHz 간격으로 파장을 촘촘히 배치한 WDM. C 밴드에 수십~100여 개 채널을 싣는다.", "optical"],
    ["코히어런트 광통신", "Coherent optical communication", "수신기의 기준 레이저로 빛의 세기뿐 아니라 위상과 두 편광까지 읽어 QPSK·16QAM 등을 쓰는 광통신. 파장당 수백 Gbps 이상을 낸다.", "optical"],
    ["FTTH", "Fiber To The Home", "통신국에서 가정 안까지 광섬유로 연결하는 방식. 대부분 PON 구조로 구축한다.", "optical"],
    ["PON", "Passive Optical Network", "전원이 필요 없는 광 분배기로 광섬유 한 가닥을 32~64가구가 나눠 쓰는 접속망. 하향은 방송, 상향은 시분할(TDMA)이다.", "optical"],
    ["해저 케이블", "Submarine cable", "바다 밑에 깐 광케이블. 50~100 km마다 EDFA 중계기를 두고 해안에서 고전압 직류로 전력을 공급하며, 대륙 간 트래픽의 대부분을 나른다.", "optical"],
    ["육양국", "Cable landing station", "해저 케이블이 바다에서 육지로 올라와 육상망과 연결되는 시설. 중계기 급전 장치도 이곳에 있다.", "optical"],
    // 06 ethernet
    ["이더넷", "Ethernet", "1973년 제록스 PARC에서 시작한 유선 근거리 통신 규칙(IEEE 802.3). 프레임 형식을 지킨 채 10 Mbps에서 1.6 Tbps까지 발전했다.", "ethernet"],
    ["이더넷 프레임", "Ethernet frame", "이더넷이 한 번에 보내는 데이터 단위. 목적지·출발지 MAC, EtherType, 46~1500바이트 페이로드, FCS로 이루어진다.", "ethernet"],
    ["EtherType", "EtherType", "이더넷 프레임 헤더의 2바이트 칸으로 페이로드의 프로토콜 종류를 알린다. 0x0800은 IPv4, 0x86DD는 IPv6, 0x0806은 ARP.", "ethernet"],
    ["MAC 주소", "MAC address", "네트워크 인터페이스마다 붙는 48비트 주소. 앞 3바이트는 제조사 OUI, 첫 바이트의 아래 두 비트는 그룹 여부와 로컬 관리 여부를 뜻한다.", "ethernet"],
    ["OUI", "Organizationally Unique Identifier", "IEEE가 제조사에 할당하는 24비트 번호로 MAC 주소의 앞 3바이트가 된다.", "ethernet"],
    ["브로드캐스트", "Broadcast", "같은 네트워크(브로드캐스트 도메인)의 모든 장치에게 보내는 전송. 이더넷에서는 목적지 MAC ff:ff:ff:ff:ff:ff를 쓴다.", "ethernet"],
    ["CSMA/CD", "Carrier Sense Multiple Access with Collision Detection", "공유 매체 이더넷의 규칙. 먼저 듣고 조용할 때 보내며, 보내는 중 충돌을 감지하면 멈추고 무작위 시간 뒤 다시 보낸다.", "ethernet"],
    ["이진 지수 백오프", "Binary exponential backoff", "n번째 충돌 뒤 0~2ⁿ−1 슬롯 중 무작위로 기다리는 방식. 충돌이 잦을수록 대기 범위가 두 배씩 넓어진다.", "ethernet"],
    ["전이중", "Full duplex", "보내기와 받기를 동시에 하는 통신. 스위치 포트와 전이중 링크에서는 충돌이 생기지 않는다.", "ethernet"],
    ["MAC 주소 테이블", "MAC address table", "스위치가 출발지 MAC과 들어온 포트를 기록해 둔 표. 목적지를 찾아 해당 포트로만 프레임을 보낸다. 오래 소식이 없으면 지운다.", "ethernet"],
    ["플러딩", "Flooding", "스위치가 목적지를 모르거나 브로드캐스트일 때 들어온 포트를 뺀 모든 포트로 프레임을 복사해 보내는 동작.", "ethernet"],
    ["충돌 도메인", "Collision domain", "동시에 보내면 신호가 부딪치는 범위. 허브는 전체가 하나, 스위치는 포트마다 따로다.", "ethernet"],
    ["브로드캐스트 도메인", "Broadcast domain", "브로드캐스트 프레임 하나가 닿는 범위. 스위치로는 나뉘지 않고 라우터나 VLAN이 나눈다.", "ethernet"],
    ["VLAN", "Virtual LAN", "스위치를 소프트웨어로 여러 개의 독립된 브로드캐스트 도메인으로 나누는 기술. VLAN 사이 통신에는 라우터가 필요하다.", "ethernet"],
    ["VLAN 태그", "802.1Q tag", "트렁크 링크에서 프레임이 어느 VLAN 것인지 표시하려고 출발지 MAC 뒤에 넣는 4바이트. 12비트 VLAN 번호(1~4094)와 3비트 우선순위를 담는다.", "ethernet"],
    ["브로드캐스트 폭풍", "Broadcast storm", "스위치 고리(루프)에서 브로드캐스트 프레임이 끝없이 돌며 복제되어 링크와 장비를 마비시키는 현상. 이더넷 프레임에 TTL이 없어서 생긴다.", "ethernet"],
    ["STP", "Spanning Tree Protocol", "스위치들이 루트 브리지를 뽑고 일부 포트를 차단해 고리 없는 트리를 만드는 프로토콜(IEEE 802.1D). 개량판은 RSTP다.", "ethernet"],
    ["루트 브리지", "Root bridge", "STP에서 브리지 ID(우선순위+MAC)가 가장 작아 트리의 뿌리가 되는 스위치.", "ethernet"],
    ["점보 프레임", "Jumbo frame", "페이로드를 1500바이트보다 크게(보통 9000바이트) 키운 이더넷 프레임. 부가 비용과 초당 프레임 수를 줄인다.", "ethernet"],
    ["링크 집계", "Link aggregation (LAG)", "여러 물리 링크를 하나의 논리 링크로 묶는 기술(IEEE 802.1AX, LACP). 한 흐름은 한 가닥으로만 가므로 흐름 하나의 속도는 늘지 않는다.", "ethernet"],
    // 07 ip
    ["최선형 전달", "best-effort delivery", "배달을 위해 노력하지만 분실·순서 뒤바뀜·중복을 막아 주지 않는 방식. 신뢰성은 TCP 같은 위 계층이 맡는다.", "ip"],
    ["CIDR", "Classless Inter-Domain Routing", "주소 뒤에 /n을 붙여 네트워크 부분의 비트 수를 자유롭게 정하는 방식. 1993년 고정 클래스를 대체했다.", "ip"],
    ["프리픽스 길이", "prefix length", "IP 주소에서 앞쪽 몇 비트가 네트워크 부분인지 나타내는 수. 192.168.0.0/24의 24.", "ip"],
    ["서브넷 마스크", "subnet mask", "네트워크 비트 자리는 1, 호스트 비트 자리는 0인 32비트 값. /24는 255.255.255.0이다.", "ip"],
    ["서브넷", "subnet", "하나의 IP 주소 블록을 프리픽스를 늘려 나눈 작은 네트워크. 같은 서브넷끼리는 라우터 없이 직접 통신한다.", "ip"],
    ["브로드캐스트 주소", "broadcast address", "호스트 비트가 모두 1인 주소. 그 서브넷의 모든 기기에게 보낼 때 쓰며 기기에게 배정할 수 없다.", "ip"],
    ["VLSM", "Variable Length Subnet Mask", "서브넷마다 프리픽스 길이를 다르게 해서 필요한 크기만큼 주소를 나눠 주는 방법.", "ip"],
    ["사설 IP 주소", "private address", "10/8, 172.16/12, 192.168/16처럼 내부망에서 자유롭게 쓰지만 인터넷으로는 직접 나갈 수 없는 주소(RFC 1918).", "ip"],
    ["루프백", "loopback", "자기 자신을 가리키는 주소(127.0.0.1, IPv6는 ::1). 보낸 패킷이 밖으로 나가지 않고 되돌아온다.", "ip"],
    ["DHCP", "Dynamic Host Configuration Protocol", "새 기기에게 IP 주소·마스크·게이트웨이·DNS를 일정 기간 임대해 주는 프로토콜. Discover·Offer·Request·ACK(DORA)로 진행된다.", "ip"],
    ["ARP", "Address Resolution Protocol", "같은 LAN에서 IP 주소에 해당하는 MAC 주소를 브로드캐스트로 물어 알아내는 프로토콜.", "ip"],
    ["NAT", "Network Address Translation", "패킷의 IP 주소를 바꿔 적는 기술. 공유기는 사설 주소를 공인 주소 하나로 바꿔 내보낸다.", "ip"],
    ["PAT", "Port Address Translation", "주소와 함께 포트 번호까지 바꿔, 공인 IP 하나를 여러 기기가 동시에 쓰게 하는 NAT. NAPT라고도 한다.", "ip"],
    ["포트 포워딩", "port forwarding", "공인 주소의 특정 포트로 들어온 연결을 내부의 정해진 기기·포트로 넘기도록 공유기에 넣는 고정 규칙.", "ip"],
    ["CGNAT", "Carrier-Grade NAT", "통신사 장비에서 하는 대규모 NAT. 여러 가입자가 공인 IP 하나를 나눠 쓴다.", "ip"],
    ["IPv6", "Internet Protocol version 6", "128비트 주소(약 3.4×10^38개)를 쓰는 차세대 IP. 16진수 8묶음을 콜론으로 잇고 ::로 축약한다.", "ip"],
    ["SLAAC", "Stateless Address Autoconfiguration", "IPv6 기기가 라우터 광고의 프리픽스에 스스로 정한 인터페이스 ID를 붙여 주소를 만드는 방법.", "ip"],
    ["듀얼 스택", "dual stack", "기기와 망이 IPv4와 IPv6를 동시에 쓰는 과도기 운영 방식.", "ip"],
    ["단편화", "fragmentation", "MTU보다 큰 IPv4 패킷을 여러 조각으로 나눠 보내는 것. 재조립은 목적지가 한다.", "ip"],
    // 08 routing
    ["라우터", "Router", "패킷의 목적지 IP를 보고 다음 장치로 넘기는 장비. 네트워크와 네트워크를 잇는다.", "routing"],
    ["데이터 평면", "data plane", "라우터에서 도착한 패킷마다 포워딩 테이블을 찾아 출력 포트로 내보내는 부분. 전용 칩이 나노초 단위로 처리한다.", "routing"],
    ["제어 평면", "control plane", "라우터에서 라우팅 프로토콜로 이웃과 정보를 주고받아 경로를 계산하고 표를 만드는 부분. CPU 위 소프트웨어가 맡는다.", "routing"],
    ["포워딩", "forwarding", "이미 만들어진 표를 보고 패킷을 알맞은 출력 포트로 넘기는 일. 표를 만드는 라우팅과 구분한다.", "routing"],
    ["라우팅 테이블", "routing table", "목적지 프리픽스별로 다음 홉과 출력 인터페이스를 적어 둔 라우터의 표.", "routing"],
    ["최장 접두사 일치", "longest prefix match", "목적지 주소와 일치하는 여러 경로 중 프리픽스가 가장 긴(가장 구체적인) 것을 고르는 규칙.", "routing"],
    ["기본 경로", "default route", "0.0.0.0/0. 모든 주소와 일치하지만 가장 짧아서 다른 일치가 없을 때만 쓰이는 경로.", "routing"],
    ["거리 벡터", "distance vector", "각 라우터가 목적지별 거리 목록을 이웃에게만 알리고, 이웃의 거리에 링크 비용을 더해 경로를 정하는 라우팅 방식. RIP이 대표다.", "routing"],
    ["벨만-포드 알고리즘", "Bellman-Ford algorithm", "이웃까지 비용 + 이웃이 말한 거리의 최솟값을 반복 계산해 최단 거리를 구하는 알고리즘. 거리 벡터 라우팅의 바탕.", "routing"],
    ["링크 상태", "link state", "각 라우터가 자기 링크 정보를 망 전체에 퍼뜨려 모두가 같은 지도를 갖고 각자 최단 경로를 계산하는 라우팅 방식.", "routing"],
    ["다익스트라 알고리즘", "Dijkstra's algorithm", "아직 확정되지 않은 노드 중 가장 가까운 것을 하나씩 확정해 나가며 한 출발점에서 모든 노드까지 최단 경로를 구하는 알고리즘.", "routing"],
    ["OSPF", "Open Shortest Path First", "기업·통신사 내부망에서 널리 쓰는 링크 상태 라우팅 프로토콜. 다익스트라로 경로를 계산한다.", "routing"],
    ["무한대로 세기", "count to infinity", "거리 벡터 라우팅에서 끊긴 목적지에 대한 낡은 정보가 이웃끼리 오가며 거리가 무한대에 닿을 때까지 조금씩 커지는 현상.", "routing"],
    ["자율 시스템", "Autonomous System (AS)", "한 조직이 하나의 라우팅 정책으로 운영하는 네트워크 묶음. 전 세계에서 유일한 AS 번호를 받는다.", "routing"],
    ["BGP", "Border Gateway Protocol", "자율 시스템 사이에서 프리픽스와 AS 경로를 주고받는 인터넷의 라우팅 프로토콜. 경로 벡터·정책 기반이다.", "routing"],
    ["트랜짓", "transit", "돈을 내고 상위 망을 통해 인터넷 전체로 가는 경로를 사는 AS 간 관계.", "routing"],
    ["피어링", "peering", "두 AS가 서로의 고객 트래픽만 대가 없이 직접 주고받는 관계.", "routing"],
    ["RPKI", "Resource Public Key Infrastructure", "주소 블록을 어느 AS가 광고할 수 있는지 전자 서명(ROA)으로 증명해, 라우터가 위조 경로를 걸러낼 수 있게 하는 체계.", "routing"],
    ["애니캐스트", "anycast", "같은 프리픽스를 여러 장소에서 동시에 광고해 사용자가 라우팅상 가장 가까운 곳으로 가게 하는 방식.", "routing"],
    // 09 tcp
    ["포트 번호", "Port Number", "한 컴퓨터 안에서 데이터를 받을 앱을 가리키는 0~65535의 16비트 번호. IP 주소가 건물이라면 포트는 호수다.", "tcp"],
    ["잘 알려진 포트", "Well-known Ports", "0~1023번 포트. HTTPS 443, DNS 53, SSH 22처럼 대표 서비스에 미리 정해진 번호다.", "tcp"],
    ["소켓", "Socket", "IP 주소와 포트 번호의 쌍, 또는 프로그램이 네트워크와 데이터를 주고받는 창구. TCP 연결은 양쪽 소켓과 프로토콜의 5-튜플로 구분된다.", "tcp"],
    ["UDP", "User Datagram Protocol", "8바이트 헤더만 붙여 연결·확인·재전송 없이 그냥 보내는 전송 프로토콜. DNS, 게임, 음성·영상 통화, QUIC의 바탕이 된다.", "tcp"],
    ["TCP", "Transmission Control Protocol", "연결을 맺고 순서 번호·확인 응답·재전송·흐름 제어·혼잡 제어로 바이트 흐름을 빠짐없이 순서대로 전달하는 전송 프로토콜.", "tcp"],
    ["3방향 핸드셰이크", "Three-way Handshake", "SYN → SYN-ACK → ACK 세 번의 교환으로 양쪽이 서로의 시작 순서 번호를 확인하고 TCP 연결을 여는 절차.", "tcp"],
    ["순서 번호", "Sequence Number", "TCP 세그먼트에 담긴 첫 바이트가 전체 바이트 흐름에서 몇 번째인지 나타내는 32비트 번호. 패킷이 아니라 바이트 단위다.", "tcp"],
    ["누적 ACK", "Cumulative ACK", "“이 번호 앞까지는 빈틈없이 다 받았다”를 알리는 확인 응답. 중간이 빠지면 같은 ACK 번호가 반복된다.", "tcp"],
    ["재전송 타임아웃", "Retransmission Timeout", "보낸 데이터의 ACK를 기다리는 제한 시간(RTO). 측정한 RTT로 계산하며, 넘으면 손실로 보고 다시 보낸다.", "tcp"],
    ["빠른 재전송", "Fast Retransmit", "같은 ACK 번호가 세 번 더(중복 ACK 3개) 오면 타임아웃을 기다리지 않고 빠진 세그먼트를 곧바로 다시 보내는 기법.", "tcp"],
    ["슬라이딩 윈도우", "Sliding Window", "확인을 받기 전에 연달아 보낼 수 있는 데이터의 범위. ACK가 오면 창이 앞으로 미끄러진다. 처리율 ≤ 윈도우/RTT.", "tcp"],
    ["흐름 제어", "Flow Control", "받는 쪽이 알려 주는 수신 윈도우(rwnd)만큼만 보내 수신 버퍼가 넘치지 않게 하는 TCP 기능.", "tcp"],
    ["혼잡 제어", "Congestion Control", "보내는 쪽이 손실·지연을 보고 네트워크 병목이 감당할 양을 추정해 전송 속도를 조절하는 기능.", "tcp"],
    ["혼잡 윈도우", "Congestion Window", "혼잡 제어를 위해 보내는 쪽이 스스로 관리하는 전송 한도(cwnd). 실제 전송량은 min(cwnd, rwnd)다.", "tcp"],
    ["슬로 스타트", "Slow Start", "작은 cwnd에서 시작해 RTT마다 두 배로 늘리는 TCP의 시작 단계. ssthresh에 닿으면 혼잡 회피로 넘어간다.", "tcp"],
    ["AIMD", "Additive Increase Multiplicative Decrease", "손실이 없으면 조금씩 더하고, 손실이 나면 곱으로 크게 줄이는 규칙. cwnd의 톱니 모양과 흐름 간 공평한 분배를 만든다.", "tcp"],
    ["CUBIC", "CUBIC", "마지막 손실 때의 윈도우 크기를 기준으로 3차 함수 모양으로 cwnd를 늘리는 혼잡 제어. 리눅스·윈도우·macOS의 기본값.", "tcp"],
    ["BBR", "Bottleneck Bandwidth and RTT", "손실 대신 병목 대역폭과 최소 RTT를 측정해 그 곱(BDP)만큼만 보내는 구글의 혼잡 제어 알고리즘.", "tcp"],
    ["헤드 오브 라인 블로킹", "Head-of-Line Blocking", "맨 앞의 데이터 하나가 늦어 그 뒤의 데이터까지 모두 기다리게 되는 현상. TCP 위 HTTP/2에서 패킷 하나의 손실이 모든 스트림을 멈추게 한다.", "tcp"],
    ["QUIC", "QUIC", "UDP 위에서 동작하며 TLS 1.3을 내장한 전송 프로토콜(RFC 9000). 1-RTT/0-RTT 연결, 독립 스트림, 연결 ID에 의한 연결 이전을 제공한다. HTTP/3의 바탕.", "tcp"],
    // 10 apps
    ["P2P", "Peer-to-Peer", "중앙 서버 없이 참가자(피어)끼리 직접 데이터를 주고받는 구조. 받는 사람이 곧 나눠 주는 사람이 되어 규모가 커져도 버틴다.", "apps"],
    ["DNS", "Domain Name System", "www.example.com 같은 이름을 IP 주소로 바꿔 주는 전 세계 분산 데이터베이스. 루트·TLD·권한 서버로 위임되는 계층 구조다.", "apps"],
    ["루트 서버", "Root Server", "DNS 계층의 맨 위. a~m.root-servers.net의 13개 이름이 있고, 애니캐스트로 전 세계 1,900곳이 넘는 곳에 복제되어 TLD 서버의 주소를 알려 준다.", "apps"],
    ["TLD", "Top-Level Domain", ".com, .org, .kr처럼 도메인 이름의 맨 오른쪽 부분. TLD 서버는 그 아래 도메인의 권한 서버를 알려 준다. 약 1,500개가 있다.", "apps"],
    ["권한 네임서버", "Authoritative Name Server", "어떤 도메인 안의 이름에 대한 정답(레코드)을 가진 DNS 서버. 도메인 주인이나 그가 맡긴 업체가 운영한다.", "apps"],
    ["재귀 리졸버", "Recursive Resolver", "사용자를 대신해 루트 → TLD → 권한 서버를 차례로 묻고, 얻은 답을 TTL 동안 캐시해 두는 DNS 서버. 통신사나 1.1.1.1·8.8.8.8 같은 공용 DNS가 운영한다.", "apps"],
    ["캐시 수명", "DNS TTL (Time To Live)", "DNS 레코드에 붙어 리졸버가 그 답을 몇 초 동안 캐시해도 되는지 정하는 값. 짧으면 변경이 빨리 퍼지고, 길면 조회가 빨라진다.", "apps"],
    ["HTTP", "HyperText Transfer Protocol", "웹의 요청·응답 프로토콜. 메서드·경로·헤더로 요청하고 상태 코드·헤더·본문으로 응답하며, 요청끼리 서로 기억하지 않는 무상태 방식이다.", "apps"],
    ["쿠키", "Cookie", "서버가 Set-Cookie로 브라우저에 맡기고 브라우저가 이후 요청마다 돌려보내는 작은 꼬리표. 무상태인 HTTP 위에 로그인 같은 세션을 만든다.", "apps"],
    ["스트림 다중화", "Stream Multiplexing", "연결 하나 안에서 여러 요청·응답(스트림)을 작은 프레임으로 쪼개 섞어 보내는 방식. HTTP/2와 HTTP/3의 핵심 기능.", "apps"],
    ["CDN", "Content Delivery Network", "전 세계 거점(PoP)의 엣지 서버에 콘텐츠 사본을 두고 사용자를 가장 가까운 엣지로 연결해 지연과 원본 서버 부담을 줄이는 네트워크.", "apps"],
    ["캐시 적중률", "Cache Hit Ratio", "요청 가운데 캐시(예: CDN 엣지)에 이미 사본이 있어 바로 응답한 비율. 높을수록 응답이 빠르고 원본 부담이 작다.", "apps"],
    ["SMTP", "Simple Mail Transfer Protocol", "메일을 보내고 메일 서버끼리 전달하는 프로토콜. 서버 간에는 25번, 사용자가 메일을 제출할 때는 587번 포트를 쓴다.", "apps"],
    ["IMAP", "Internet Message Access Protocol", "메일 서버의 사서함을 들여다보며 메일을 읽는 프로토콜. 메일이 서버에 남아 여러 기기에서 같은 상태를 본다(암호화 시 993번).", "apps"],
    ["웹소켓", "WebSocket", "HTTP 요청으로 시작해 하나의 TCP 연결을 양쪽이 아무 때나 메시지를 보낼 수 있는 양방향 통로로 바꾸는 프로토콜. 채팅·실시간 알림에 쓴다.", "apps"],
    ["적응형 비트레이트", "Adaptive Bitrate Streaming", "영상을 여러 화질로 미리 인코딩해 두고 조각(세그먼트)마다 네트워크 상황과 버퍼에 맞는 화질을 골라 받는 스트리밍 방식(HLS, MPEG-DASH).", "apps"],
    ["재버퍼링", "Rebuffering", "재생 버퍼가 바닥나 동영상이 멈추고 데이터를 기다리는 상태. 시청자 경험을 가장 크게 해친다.", "apps"],
    ["비트토렌트", "BitTorrent", "파일을 조각으로 나눠 받는 사람끼리 서로 주고받게 하는 P2P 파일 배포 프로토콜. 희귀 조각 우선, 맞대응 규칙을 쓴다.", "apps"],
    // 11 radio
    ["전자기파", "Electromagnetic wave", "전기장과 자기장이 서로를 만들어 내며 빛의 속도로 퍼져 나가는 파동. 전파·빛·X선은 주파수만 다른 같은 전자기파다.", "radio"],
    ["반파장 다이폴", "Half-wave dipole", "길이가 파장의 절반인 막대 두 개로 된 가장 기본적인 안테나. 이득은 약 2.15 dBi이고 도넛 모양으로 방사한다.", "radio"],
    ["안테나", "Antenna", "도선 속 교류 전류를 공간을 날아가는 전파로 바꾸거나, 그 반대로 바꾸는 장치. 송신과 수신에서 성질이 같다.", "radio"],
    ["방사 패턴", "Radiation pattern", "안테나가 방향별로 전파를 얼마나 세게 내보내는지(받는지)를 나타낸 그림.", "radio"],
    ["안테나 이득", "Antenna gain", "가장 센 방향의 세기가 모든 방향으로 고르게 내보내는 등방성 안테나보다 몇 배인지를 dBi로 나타낸 값. 전력을 만들지 않고 한 방향으로 모은다.", "radio"],
    ["자유 공간 경로 손실", "Free-space path loss (FSPL)", "장애물 없는 공간에서 거리와 주파수에 따라 줄어드는 전력. 20log d + 20log f + 32.45 (km, MHz)로 거리 2배마다 6 dB 커진다.", "radio"],
    ["링크 버짓", "Link budget", "송신 출력과 안테나 이득에서 각종 손실을 빼 수신 전력을 구하고, 수신 감도와 비교해 여유를 따지는 데시벨 가계부.", "radio"],
    ["수신 감도", "Receiver sensitivity", "수신기가 정해진 속도와 오류율로 신호를 받아 낼 수 있는 최소 수신 전력(dBm).", "radio"],
    ["회절", "Diffraction", "파동이 장애물의 모서리를 돌아 그림자 영역으로 휘어 들어가는 현상. 파장이 길수록 잘 일어난다.", "radio"],
    ["전리층", "Ionosphere", "햇빛에 이온화된 고도 약 60~400 km의 대기층. 단파(HF)를 거울처럼 반사해 대륙 간 통신을 가능하게 한다.", "radio"],
    ["다중 경로", "Multipath", "전파가 직접 경로와 여러 반사·산란 경로로 나뉘어 시간차를 두고 도착하는 현상.", "radio"],
    ["페이딩", "Fading", "다중 경로 간섭이나 이동 때문에 수신 신호 세기가 위치·시간에 따라 크게 출렁이는 현상.", "radio"],
    ["레일리 페이딩", "Rayleigh fading", "직접파 없이 비슷한 세기의 산란파가 많이 섞일 때의 페이딩. 신호 크기가 레일리 분포를 따르며 깊은 골이 자주 생긴다.", "radio"],
    ["다이버시티", "Diversity", "서로 독립적으로 출렁이는 여러 안테나·주파수·시간의 신호를 골라 쓰거나 합쳐 페이딩을 이겨 내는 기법.", "radio"],
    ["도플러 효과", "Doppler effect", "송신기나 수신기가 움직일 때 받는 주파수가 v/c × f만큼 바뀌는 현상.", "radio"],
    ["면허 대역", "Licensed band", "국가로부터 독점 사용권을 받아야 쓸 수 있는 주파수 대역. 이동통신 주파수는 주로 경매로 할당한다.", "radio"],
    ["비면허 대역", "Unlicensed band", "출력 등 기술 기준만 지키면 허가 없이 누구나 쓸 수 있는 주파수 대역. Wi-Fi와 블루투스가 쓴다.", "radio"],
    ["ISM 대역", "ISM band", "산업·과학·의료용으로 지정된 비면허 대역. 2.4 GHz 대역이 대표적이며 전자레인지와 Wi-Fi가 함께 쓴다.", "radio"],
    ["SAR", "Specific Absorption Rate", "전자파 흡수율. 몸 조직 1 kg이 흡수하는 전력(W/kg). 한국 기준은 머리·몸통 1 g 평균 1.6 W/kg이다.", "radio"],
    // 12 modulation
    ["반송파", "Carrier", "메시지를 실어 나르는 높은 주파수의 사인파. 안테나를 작게 하고 주파수를 나눠 쓰게 해 준다.", "modulation"],
    ["변조", "Modulation", "메시지에 따라 반송파의 진폭·주파수·위상을 바꿔 정보를 싣는 일. 받는 쪽에서 꺼내는 일은 복조라 한다.", "modulation"],
    ["진폭 변조", "Amplitude Modulation (AM)", "메시지에 따라 반송파의 세기를 바꾸는 아날로그 변조. 단순하지만 잡음에 약하다.", "modulation"],
    ["주파수 변조", "Frequency Modulation (FM)", "메시지에 따라 반송파의 주파수를 바꾸는 아날로그 변조. 잡음에 강하지만 대역폭을 많이 쓴다.", "modulation"],
    ["PSK", "Phase Shift Keying", "위상 편이 변조. 심볼마다 반송파의 위상을 바꿔 비트를 싣는다. BPSK는 0°/180° 두 가지를 쓴다.", "modulation"],
    ["I/Q", "In-phase / Quadrature", "서로 90° 어긋난 코사인(I)과 사인(Q) 두 성분. 두 값의 조합으로 어떤 진폭·위상의 신호든 표현한다.", "modulation"],
    ["성좌도", "Constellation diagram", "변조에서 쓰는 심볼들을 I/Q 평면 위의 점으로 그린 그림. 점 개수가 M이면 심볼당 log₂M 비트를 싣는다.", "modulation"],
    ["직교 진폭 변조", "Quadrature Amplitude Modulation (QAM)", "I와 Q의 진폭을 여러 단계로 바꿔 점을 격자로 배치하는 변조. 16QAM은 4비트, 4096QAM은 12비트를 싣는다.", "modulation"],
    ["그레이 코드", "Gray code", "이웃한 값끼리 1비트만 다르게 배정하는 부호. 성좌도에서 이웃 점으로 잘못 읽어도 비트 오류가 1개로 그친다.", "modulation"],
    ["적응 변조", "Adaptive Modulation and Coding (AMC)", "채널 상태(SNR)에 맞춰 변조 차수와 부호율을 계속 바꿔 가장 빠르면서도 오류가 적은 조합을 고르는 기법.", "modulation"],
    ["MCS", "Modulation and Coding Scheme", "변조 방식과 부호율의 조합에 붙인 번호. Wi-Fi 7은 MCS 0(BPSK 1/2)~13(4096QAM 5/6)을 쓴다.", "modulation"],
    ["부호율", "Code rate", "전송 비트 가운데 실제 데이터의 비율. 3/4이면 4비트 중 1비트가 오류 정정용 여분이다.", "modulation"],
    ["OFDM", "Orthogonal Frequency Division Multiplexing", "넓은 채널을 서로 직교하는 수많은 좁은 부반송파로 나눠 동시에 보내는 방식. Wi-Fi·LTE·5G의 바탕이다.", "modulation"],
    ["부반송파", "Subcarrier", "OFDM에서 채널을 잘게 나눈 각각의 좁은 반송파. 저마다 QAM 심볼 하나를 싣는다.", "modulation"],
    ["사이클릭 프리픽스", "Cyclic prefix (CP)", "OFDM 심볼 끝부분을 복사해 앞에 붙인 완충 구간. 다중 경로 메아리가 다음 심볼을 침범하지 않게 한다.", "modulation"],
    ["OFDMA", "Orthogonal Frequency Division Multiple Access", "OFDM의 시간×주파수 자원을 여러 사용자에게 나눠 주는 다중 접속 방식.", "modulation"],
    ["자원 블록", "Resource block", "OFDMA에서 스케줄러가 사용자에게 나눠 주는 시간×주파수 격자의 한 칸(부반송파 묶음 × 일정 시간).", "modulation"],
    ["확산 스펙트럼", "Spread spectrum", "신호를 빠른 코드로 곱해 넓은 대역에 얇게 퍼뜨리는 기법. 잡음·방해에 강하고 GPS와 CDMA가 쓴다.", "modulation"],
    ["CDMA", "Code Division Multiple Access", "모든 사용자가 같은 주파수·시간을 쓰되 서로 직교하는 코드로 구분하는 다중 접속 방식. 3G의 핵심이었다.", "modulation"],
    ["MIMO", "Multiple-Input Multiple-Output", "송수신 안테나를 여러 개 써서 다이버시티, 공간 다중화, 빔포밍을 하는 기술.", "modulation"],
    ["공간 다중화", "Spatial multiplexing", "MIMO에서 여러 안테나로 서로 다른 데이터 스트림을 같은 주파수·시간에 보내 처리율을 스트림 수만큼 늘리는 방법.", "modulation"],
    ["빔포밍", "Beamforming", "배열 안테나 각 소자의 위상을 조절해 특정 방향으로 에너지를 모으는 기술. 소자 수 N이면 이득은 약 10log N dB.", "modulation"],
    ["Massive MIMO", "Massive MIMO", "기지국에 수십~수백 개의 안테나 소자(예: 64T64R)를 두고 여러 사용자에게 동시에 빔을 보내는 5G 기술.", "modulation"],
    // 13 wifi
    ["액세스 포인트", "Access Point (AP)", "무선 단말과 유선 이더넷 사이를 이어 주는 장비. Wi-Fi 프레임을 이더넷 프레임으로 바꿔 넘긴다. 공유기 안에도 들어 있다.", "wifi"],
    ["비컨", "Beacon", "AP가 약 0.1초(102.4 ms)마다 방송하는 안내 프레임. SSID, 지원 속도, 보안 방식, 채널 정보를 담는다.", "wifi"],
    ["SSID", "Service Set Identifier", "Wi-Fi 네트워크의 이름. 비컨에 실려 방송되며 휴대폰 Wi-Fi 목록에 보이는 이름이 이것이다.", "wifi"],
    ["4-way 핸드셰이크", "4-way handshake", "WPA2/WPA3에서 AP와 단말이 난수 두 개를 주고받아 이번 연결에만 쓸 암호 키를 각자 계산하는 4단계 교환. 비밀번호는 전파로 나가지 않는다.", "wifi"],
    ["채널 본딩", "Channel bonding", "이웃한 20 MHz 채널을 묶어 40·80·160·320 MHz의 넓은 채널로 쓰는 것. 속도는 늘지만 쓸 수 있는 채널 수는 준다.", "wifi"],
    ["CSMA/CA", "Carrier Sense Multiple Access with Collision Avoidance", "먼저 채널을 듣고, 조용하면 무작위 백오프만큼 기다린 뒤 보내며, ACK로 성공을 확인하는 Wi-Fi의 매체 접근 규칙.", "wifi"],
    ["백오프", "Backoff", "충돌을 피하려고 0~CW 사이의 무작위 슬롯 수만큼 기다리는 것. 충돌할 때마다 CW를 두 배로 늘린다(지수 백오프).", "wifi"],
    ["숨은 노드 문제", "Hidden node problem", "두 단말이 AP에는 닿지만 서로의 신호는 듣지 못해, 동시에 보내 AP에서 충돌하는 문제. RTS/CTS로 완화한다.", "wifi"],
    ["RTS/CTS", "Request to Send / Clear to Send", "긴 프레임을 보내기 전 짧은 예약 요청(RTS)과 허가(CTS)를 주고받아, 숨은 단말까지 그 시간 동안 침묵(NAV)하게 하는 방식.", "wifi"],
    ["프레임 집적", "Frame aggregation (A-MPDU)", "여러 프레임을 한 번의 전송에 묶어 보내 프리앰블·대기·ACK 같은 고정 오버헤드를 나눠 갖게 하는 기법. 실제 속도의 핵심.", "wifi"],
    ["메시 Wi-Fi", "Mesh Wi-Fi", "여러 AP 노드가 같은 SSID를 내보내고 서로 무선·유선으로 이어져 하나의 망처럼 집 전체를 덮는 방식.", "wifi"],
    ["로밍", "Roaming", "단말이 연결을 유지한 채 한 AP에서 다른 AP로 옮겨 가는 것. Wi-Fi에서는 단말이 결정하며 802.11k/v/r이 돕는다.", "wifi"],
    ["TWT", "Target Wake Time", "AP와 단말이 다음에 깨어날 시각을 약속해, 그 사이 단말이 무선부를 꺼 두도록 하는 Wi-Fi 6의 절전 기능.", "wifi"],
    ["MLO", "Multi-Link Operation", "Wi-Fi 7에서 한 연결이 2.4·5·6 GHz 등 여러 대역의 링크를 동시에 쓰는 기능. 속도를 더하고 지연을 줄인다.", "wifi"],
    ["주파수 도약", "Frequency hopping", "짧은 시간마다 정해진 순서로 채널을 바꿔 가며 통신해 간섭과 도청을 피하는 방식. 클래식 블루투스는 79개 채널을 초당 1,600번 옮긴다.", "wifi"],
    ["BLE", "Bluetooth Low Energy", "대부분의 시간을 잠자고 수 ms만 깨어나 보내는 저전력 블루투스. 2 MHz 채널 40개를 쓰며 코인 전지로 수년 동작한다.", "wifi"],
    ["Matter", "Matter", "제조사가 달라도 스마트홈 기기를 같은 방식으로 제어하게 하는 응용 계층 표준. Wi-Fi·Thread·이더넷 위에서 동작한다.", "wifi"],
    ["LoRa", "Long Range", "1 GHz 아래 비면허 대역에서 신호를 넓게 확산해 수 km를 수 kbps로, 배터리 수년으로 보내는 저전력 장거리 무선 방식.", "wifi"],
    // 14 cellular
    ["셀", "Cell", "기지국 하나가 맡는 지역. 땅을 셀로 잘게 나누면 멀리 떨어진 셀끼리 같은 주파수를 다시 쓸 수 있다.", "cellular"],
    ["주파수 재사용", "Frequency reuse", "충분히 떨어진 셀에서 같은 주파수를 다시 쓰는 것. 재사용 계수 N이 작을수록 셀당 채널은 많지만 간섭이 커진다. LTE·5G는 N=1에 가깝게 쓰고 간섭을 신호 처리로 다룬다.", "cellular"],
    ["셀 분할", "Cell splitting", "셀을 더 작게 나눠 같은 면적에 기지국을 더 세우는 것. 같은 주파수로 수용할 수 있는 사용자가 늘어난다.", "cellular"],
    ["핸드오버", "Handover", "통화·데이터 연결을 끊지 않고 이동 중인 단말을 한 기지국에서 이웃 기지국으로 넘기는 절차. 히스테리시스로 핑퐁을 막는다.", "cellular"],
    ["gNB", "gNodeB", "5G 기지국. LTE의 기지국은 eNB(eNodeB)라 부른다. 무선 구간을 맡고 백홀로 코어망에 연결된다.", "cellular"],
    ["코어망", "Core network (EPC/5GC)", "기지국 뒤에서 가입자 인증, 이동성 관리, 세션 관리, 인터넷 연결을 맡는 통신사 중심 네트워크. 5G 코어(5GC)는 클라우드형 소프트웨어 기능으로 구성된다.", "cellular"],
    ["AMF", "Access and Mobility Management Function", "5G 코어에서 단말의 접속 등록, 인증 연계, 이동성(어느 기지국 근처에 있는지)을 관리하는 기능.", "cellular"],
    ["UPF", "User Plane Function", "5G 코어에서 실제 사용자 데이터 패킷을 인터넷 쪽으로 전달하는 기능. 지연을 줄이려 엣지 가까이 두기도 한다.", "cellular"],
    ["SIM 카드", "SIM / eSIM", "가입자 식별 번호와 비밀 키를 담은 작은 보안 칩. 망은 이 키로 단말을 인증하고 암호 키를 만든다. eSIM은 칩을 기기에 내장하고 프로필을 내려받는다.", "cellular"],
    ["URLLC", "Ultra-Reliable Low-Latency Communications", "5G의 세 가지 목표 중 하나. 공장 자동화·원격 제어처럼 1 ms 수준 지연과 매우 높은 신뢰성이 필요한 통신. 나머지 둘은 eMBB(초고속)와 mMTC(대량 사물 연결).", "cellular"],
    ["뉴멀로지", "Numerology", "5G NR에서 부반송파 간격(15·30·60·120 kHz…)과 그에 따른 심볼·슬롯 길이의 조합. 간격이 넓을수록 슬롯이 짧아져 지연이 줄고 고주파에 유리하다.", "cellular"],
    ["밀리미터파", "Millimeter wave (mmWave)", "파장이 수 mm인 24 GHz 이상 대역(5G의 28·39 GHz 등). 대역폭이 넓어 매우 빠르지만 멀리 못 가고 벽·몸에 쉽게 막힌다.", "cellular"],
    ["O-RAN", "Open RAN", "기지국을 표준 인터페이스로 나눠(무선부·분산부·중앙부) 여러 회사 장비를 섞어 쓰고 범용 서버에서 소프트웨어로 돌리려는 흐름.", "cellular"],
    ["네트워크 슬라이싱", "Network slicing", "하나의 물리 5G망을 용도별로 성능이 보장되는 여러 가상망(슬라이스)으로 나눠 쓰는 기술.", "cellular"],
    ["TDD/FDD", "Time/Frequency Division Duplex", "송수신을 나누는 두 방식. FDD는 상·하향에 다른 주파수를, TDD는 같은 주파수를 시간으로 나눠 쓴다. 한국 5G 3.5 GHz는 TDD.", "cellular"],
    // 15 satellite
    ["정지 궤도", "GEO (Geostationary Orbit)", "적도 위 고도 35,786 km의 궤도. 지구 자전과 같은 주기로 돌아 땅에서 보면 하늘의 한 점에 멈춰 있다. 왕복 지연이 최소 약 0.48초다.", "satellite"],
    ["중궤도", "MEO (Medium Earth Orbit)", "고도 약 2,000~35,786 km 사이의 궤도. GPS 위성(약 20,200 km)과 일부 통신 위성이 쓴다.", "satellite"],
    ["저궤도", "LEO (Low Earth Orbit)", "고도 약 300~2,000 km의 궤도. 지연이 짧고 신호가 강하지만 한 지점 위를 몇 분 만에 지나가므로 많은 위성이 필요하다.", "satellite"],
    ["케플러 제3법칙", "Kepler's Third Law", "궤도 주기의 제곱이 궤도 반지름의 세제곱에 비례한다는 법칙. 위성이 높을수록 훨씬 느리게 도는 이유다.", "satellite"],
    ["커버리지", "Coverage", "위성이나 기지국의 신호를 쓸 수 있는 지역. 위성에서는 정해진 최소 앙각 이상으로 위성이 보이는 지역의 크기로 정한다.", "satellite"],
    ["위성 군집", "Satellite Constellation", "여러 궤도면에 많은 위성을 일정한 간격으로 배치해 함께 운용하는 위성 무리. 스타링크, 원웹, 카이퍼가 대표적이다.", "satellite"],
    ["벤트 파이프", "Bent Pipe", "위성이 받은 신호를 처리하지 않고 주파수만 바꿔 그대로 지상으로 되돌려 보내는 방식. 근처에 지상국이 있어야 한다.", "satellite"],
    ["위성 간 링크", "ISL (Inter-Satellite Link)", "위성끼리 직접 레이저나 전파로 연결하는 링크. 지상국 없이 위성에서 위성으로 데이터를 중계해 바다 위에서도 서비스할 수 있다.", "satellite"],
    ["위상 배열 안테나", "Phased Array Antenna", "작은 안테나 소자 여러 개의 위상을 조절해 빔 방향을 전자식으로 바꾸는 평판 안테나. 움직이는 부품 없이 위성을 따라간다.", "satellite"],
    ["Ku 대역", "Ku Band", "약 12~18 GHz 마이크로파 대역. 위성 TV와 저궤도 위성 인터넷의 사용자 링크에 널리 쓴다.", "satellite"],
    ["Ka 대역", "Ka Band", "약 26.5~40 GHz 마이크로파 대역. 넓은 대역폭으로 대용량 위성 통신에 쓰지만 비에 의한 감쇠가 크다.", "satellite"],
    ["비 감쇠", "Rain Fade", "빗방울이 전파를 흡수·산란해 위성 신호가 약해지는 현상. 주파수가 높을수록, 비가 강할수록, 앙각이 낮을수록 심하다.", "satellite"],
    ["위성 직접 연결", "Direct-to-Cell", "별도 위성 단말 없이 일반 휴대폰이 위성과 직접 통신하는 서비스. 위성 쪽에 큰 안테나를 달아 약한 휴대폰 신호를 받는다.", "satellite"],
    ["비지상 네트워크", "NTN (Non-Terrestrial Network)", "위성이나 고고도 비행체를 이동통신망의 일부로 쓰는 3GPP 표준 개념. Release 17(2022)에서 5G에 처음 들어갔다.", "satellite"],
    ["GNSS", "Global Navigation Satellite System", "위성 항법 시스템의 총칭. 미국 GPS, 러시아 GLONASS, 유럽 Galileo, 중국 BeiDou 등이 있다.", "satellite"],
    ["삼변측량", "Trilateration", "여러 기준점까지의 거리로 위치를 구하는 방법. GPS는 위성까지의 거리를 신호 도착 시간으로 잰다.", "satellite"],
    ["원자시계", "Atomic Clock", "원자의 고유한 진동수를 기준으로 삼는 매우 정확한 시계. GPS 위성마다 실려 있어 나노초 수준의 시각을 방송한다.", "satellite"],
    ["케슬러 증후군", "Kessler Syndrome", "궤도의 파편이 충돌해 더 많은 파편을 만들고, 그 파편이 또 충돌하는 연쇄 반응. 특정 고도를 오래 쓸 수 없게 만들 수 있다.", "satellite"],
    // 16 serdes
    ["SerDes", "Serializer/Deserializer", "병렬 데이터를 한 줄로 늘어세워 고속으로 보내고(직렬화), 받은 쪽에서 다시 병렬로 펼치는(역직렬화) 회로. 오늘날에는 등화·클럭 복원·FEC까지 포함한 고속 송수신기 전체를 가리킨다.", "serdes"],
    ["스큐", "Skew", "같은 순간 출발한 신호들이 선 길이·환경 차이 때문에 서로 다른 시각에 도착하는 어긋남.", "serdes"],
    ["레인", "Lane", "고속 직렬 링크의 기본 단위. 송신용 차동 쌍 하나와 수신용 차동 쌍 하나로 이루어진다. 포트 속도 = 레인 수 × 레인 속도.", "serdes"],
    ["보 레이트", "Baud rate", "1초에 보내는 기호(심볼)의 수. 단위는 Bd. 비트 레이트 = 보 레이트 × 기호당 비트 수.", "serdes"],
    ["PAM4", "4-level Pulse Amplitude Modulation", "전압 4단계로 기호당 2비트를 보내는 방식. 같은 보 레이트에 두 배의 비트를 싣지만 눈 높이가 1/3로 줄어 약 9.5 dB 잡음에 약해진다.", "serdes"],
    ["나이퀴스트 주파수", "Nyquist frequency", "보 레이트의 절반. 신호가 가장 빠르게 바뀔 때의 기본 주파수로, 채널 손실을 이 주파수에서 따진다.", "serdes"],
    ["삽입 손실", "Insertion loss", "신호가 채널(배선·커넥터·케이블)을 지나며 잃는 세기를 dB로 나타낸 값. 주파수가 높을수록 커진다.", "serdes"],
    ["심볼 간 간섭", "ISI, Inter-Symbol Interference", "채널을 지나며 퍼진 펄스의 꼬리가 이웃 비트 자리에 겹쳐 값을 헷갈리게 만드는 현상.", "serdes"],
    ["이퀄라이저", "Equalizer", "채널이 깎아 먹은 고주파를 되살리거나 ISI를 빼 주어 닫힌 눈을 다시 여는 회로. FFE·CTLE·DFE가 대표적이다.", "serdes"],
    ["FFE", "Feed-Forward Equalizer", "현재 비트에 앞뒤 비트를 일정 비율 빼서 섞는 유한 탭 필터. 송신 쪽(디엠퍼시스)과 수신 DSP에 쓰인다.", "serdes"],
    ["CTLE", "Continuous-Time Linear Equalizer", "수신 입구의 아날로그 필터로 저주파를 깎아 고주파를 상대적으로 키운다. 잡음도 함께 키우는 단점이 있다.", "serdes"],
    ["DFE", "Decision Feedback Equalizer", "이미 판정한 이전 비트들이 남긴 꼬리를 계산해 빼 주는 등화기. 잡음을 키우지 않지만 판정 오류가 번질 수 있다.", "serdes"],
    ["CDR", "Clock and Data Recovery", "별도 클럭선 없이 데이터의 전이 시각에서 박자를 뽑아내 샘플링 위치를 눈 중심에 맞추는 회로.", "serdes"],
    ["지터", "Jitter", "신호 전이나 클럭의 박자가 이상적인 시각에서 들쭉날쭉 벗어나는 흔들림.", "serdes"],
    ["리드-솔로몬 부호", "Reed-Solomon code", "여러 비트를 한 심볼로 묶어 패리티 심볼을 붙이는 오류 정정 부호. 이더넷의 RS(544,514) KP4는 심볼 15개까지 고친다.", "serdes"],
    ["반사 계수", "Reflection coefficient", "임피던스가 바뀌는 지점에서 되튕기는 전압의 비율. Γ = (R − Z₀)/(R + Z₀).", "serdes"],
    ["AEC", "Active Electrical Cable", "커넥터 안에 리타이머 칩을 넣어 수동 구리 케이블(DAC)보다 멀리 가는 능동 구리 케이블.", "serdes"],
    ["UCIe", "Universal Chiplet Interconnect Express", "한 패키지 안의 칩렛끼리 넓은 병렬 배선으로 잇는 개방형 표준. 비트당 에너지가 매우 낮다.", "serdes"],
    // 17 netchips
    ["스위치 ASIC", "Switch ASIC", "스위치·라우터의 데이터 평면을 맡는 전용 칩. 수백 개의 SerDes, 패킷 처리 파이프라인, 검색 표, 공유 버퍼를 한 다이(또는 칩렛 묶음)에 담는다.", "netchips"],
    ["머천트 실리콘", "Merchant silicon", "칩 회사가 여러 장비 회사에 공개적으로 파는 범용 스위치 칩. 장비 회사·클라우드 회사가 자기 장비에만 쓰는 자체 칩과 대비된다.", "netchips"],
    ["패킷 처리 파이프라인", "Packet processing pipeline", "패킷 처리를 파서, 여러 매치-액션 단계, 트래픽 매니저, 디파서로 잘게 나눠 조립 라인처럼 늘어놓은 구조. 매 사이클 새 패킷을 받아들인다.", "netchips"],
    ["파서", "Parser", "패킷 앞부분의 바이트열을 읽어 이더넷·IP·TCP 등 헤더를 알아보고 필드를 뽑아내는 파이프라인의 첫 단계.", "netchips"],
    ["매치-액션 테이블", "Match-action table", "헤더 필드를 키로 표를 검색(match)하고, 찾은 항목에 적힌 동작(action: 포트 지정, 헤더 수정, 버리기 등)을 실행하는 파이프라인 단계.", "netchips"],
    ["트래픽 매니저", "Traffic manager", "스위치 칩에서 패킷을 출력 포트별 큐에 넣고 버퍼를 관리하며, 스케줄러로 꺼낼 순서를 정하는 블록.", "netchips"],
    ["P4", "Programming Protocol-independent Packet Processors", "스위치의 파서와 매치-액션 파이프라인이 무엇을 할지 기술하는 프로그래밍 언어.", "netchips"],
    ["TCAM", "Ternary Content-Addressable Memory", "비트마다 0·1·X(상관없음)를 저장하고, 검색 키를 모든 줄과 한 사이클에 동시에 비교하는 메모리. ACL과 최장 접두사 일치에 쓰지만 면적과 전력이 크다.", "netchips"],
    ["우선순위 인코더", "Priority encoder", "여러 일치 신호 중 가장 우선순위가 높은(가장 위의) 것 하나의 번호를 골라 내는 회로.", "netchips"],
    ["마이크로버스트", "Microburst", "수 µs~수백 µs 동안만 트래픽이 몰려 큐가 순간적으로 넘치는 현상. 평균 사용률 그래프에는 잘 보이지 않는다.", "netchips"],
    ["공유 버퍼", "Shared buffer", "스위치 칩의 패킷 버퍼를 포트마다 고정 분할하지 않고 전체가 함께 쓰게 해, 붐비는 포트가 더 많이 쓰도록 한 구조.", "netchips"],
    ["NIC", "Network Interface Card", "컴퓨터를 네트워크에 연결하는 장치. PHY·MAC과 DMA, 각종 오프로드 기능을 갖춘다.", "netchips"],
    ["DMA", "Direct Memory Access", "CPU를 거치지 않고 장치가 메모리에 직접 데이터를 읽고 쓰는 방식.", "netchips"],
    ["TSO", "TCP Segmentation Offload", "운영체제가 넘긴 큰 데이터 덩어리를 NIC가 MTU 크기 패킷들로 잘라 헤더를 붙여 주는 기능. 받는 쪽에서 합치는 것은 LRO/GRO.", "netchips"],
    ["RSS", "Receive Side Scaling", "수신 패킷의 헤더를 해시해 흐름마다 다른 수신 큐와 CPU 코어로 나눠 주는 NIC 기능.", "netchips"],
    ["SR-IOV", "Single Root I/O Virtualization", "PCIe 장치 하나를 여러 개의 가상 기능(VF)으로 나눠 가상 머신이 직접 쓰게 하는 기술.", "netchips"],
    ["SmartNIC", "SmartNIC", "프로그래머블 파이프라인이나 FPGA를 얹어 가상 스위치·터널 처리 같은 네트워크 기능을 하드웨어로 떼어 가는 NIC.", "netchips"],
    ["DPU", "Data Processing Unit", "NIC에 범용 Arm 코어, 메모리, 암호·스토리지 가속기를 더해 서버의 인프라 작업(네트워크·보안·스토리지)을 대신 실행하는 칩. IPU라고도 한다.", "netchips"],
    ["레티클 한계", "Reticle limit", "노광 장비가 한 번에 찍을 수 있는 최대 칩 크기(약 26 × 33 mm, 858 mm²). 이보다 큰 칩은 여러 다이로 나눠야 한다.", "netchips"],
    // 18 rfchips
    ["RF 프런트엔드", "RF front-end (RFFE)", "안테나 바로 뒤에서 안테나 스위치·튜너, 대역별 필터와 듀플렉서, 전력 증폭기, 저잡음 증폭기를 묶은 부분. 휴대폰에서는 여러 재료의 칩을 한 모듈에 넣는다.", "rfchips"],
    ["믹서", "Mixer", "두 신호를 곱해 합·차 주파수를 만드는 회로. 수신 신호를 국부 발진기와 곱해 낮은 주파수로 내리거나, 송신 신호를 높은 주파수로 올린다.", "rfchips"],
    ["국부 발진기", "Local oscillator (LO)", "믹서에 곱해 주는 깨끗한 기준 사인파. 보통 PLL로 만들며, 주파수를 바꿔 원하는 채널을 고른다.", "rfchips"],
    ["중간 주파수", "Intermediate frequency (IF)", "슈퍼헤테로다인 수신기에서 수신 주파수와 LO 주파수의 차로 얻는 고정된 중간 단계 주파수. 여기서 날카로운 필터로 이웃 신호를 걷어 낸다.", "rfchips"],
    ["이미지 주파수", "Image frequency", "LO를 사이에 두고 원하는 신호와 거울 대칭인 주파수(2·f_LO − f_RF). 믹서를 거치면 원하는 신호와 같은 IF로 내려와 겹치므로 믹서 앞에서 걸러야 한다.", "rfchips"],
    ["직접 변환 수신기", "Direct-conversion (zero-IF) receiver", "LO를 신호 주파수와 같게 놓아 곧장 0 Hz 근처로 내리는 수신기. 90° 어긋난 두 LO로 I와 Q를 얻으며, 오늘날 휴대폰 트랜시버의 기본 구조다.", "rfchips"],
    ["전압 제어 발진기", "Voltage-controlled oscillator (VCO)", "입력 전압에 따라 출력 주파수가 바뀌는 발진기. 주파수를 넓게 바꿀 수 있지만 혼자서는 불안정해 PLL로 묶어 쓴다.", "rfchips"],
    ["위상 고정 루프", "Phase-locked loop (PLL)", "VCO 출력을 N으로 나눈 신호를 수정 발진기와 계속 비교해 VCO를 고정하는 되먹임 회로. 출력 주파수는 N × 기준 주파수가 된다.", "rfchips"],
    ["위상 잡음", "Phase noise", "발진기 출력의 위상이 무작위로 흔들리는 현상. 스펙트럼에서는 반송파 옆의 치마로, 성좌도에서는 점들이 원 방향으로 번지는 모습으로 나타난다. 단위 dBc/Hz.", "rfchips"],
    ["전력 증폭기", "Power amplifier (PA)", "송신 신호를 안테나로 내보낼 만큼 크게 키우는 증폭기. 휴대폰 PA는 주로 GaAs HBT, 기지국 PA는 GaN HEMT로 만든다.", "rfchips"],
    ["전력 부가 효율", "Power-added efficiency (PAE)", "(출력 RF 전력 − 입력 RF 전력) ÷ 공급 직류 전력. PA가 배터리 전력을 얼마나 전파로 바꾸는지 나타낸다.", "rfchips"],
    ["백오프", "Back-off", "신호의 순간 봉우리가 찌그러지지 않도록 PA의 평균 출력을 포화점보다 낮춰 쓰는 정도(dB). 크게 하면 선형성은 좋아지고 효율은 떨어진다.", "rfchips"],
    ["포락선 추적", "Envelope tracking (ET)", "신호 크기(포락선)에 맞춰 PA의 공급 전압을 실시간으로 오르내려 효율을 높이는 기술.", "rfchips"],
    ["디지털 전치 왜곡", "Digital pre-distortion (DPD)", "PA의 비선형 왜곡을 미리 측정해 디지털 단계에서 반대로 찌그러뜨려 보내 상쇄하는 기술. 백오프를 줄여 효율을 높인다.", "rfchips"],
    ["잡음 지수", "Noise figure (NF)", "회로를 통과하며 신호 대 잡음비가 몇 dB 나빠지는지 나타내는 값. 여러 단의 전체 값은 프리스 공식으로 계산한다.", "rfchips"],
    ["저잡음 증폭기", "Low-noise amplifier (LNA)", "수신 경로의 첫 단에서 자신의 잡음을 최소로 보태며 약한 신호를 키우는 증폭기. 전체 잡음 지수를 사실상 결정한다.", "rfchips"],
    ["듀플렉서", "Duplexer", "송신 필터와 수신 필터를 하나로 묶어, 한 안테나로 서로 다른 주파수에서 동시에 송수신하게 하는 부품(FDD).", "rfchips"],
    ["SAW 필터", "Surface acoustic wave filter", "압전 기판 표면의 빗살 전극으로 전기 신호를 표면 음파로 바꿔 거르는 필터. 싸고 성숙했으며 주로 약 2.5 GHz 이하에 쓴다.", "rfchips"],
    ["BAW 필터", "Bulk acoustic wave filter", "AlN 같은 압전 박막을 두께 방향으로 공진시켜 거르는 필터. Q가 높고 6 GHz 근처까지 쓸 수 있다. FBAR와 SMR이 대표 구조다.", "rfchips"],
    ["RF-SOI", "RF silicon-on-insulator", "얇은 산화막 위에 실리콘 소자를 만든 RF용 웨이퍼 공정. 기판 손실과 기생 용량이 작아 안테나 스위치·튜너·LNA에 널리 쓴다.", "rfchips"],
    ["유효 비트 수", "Effective number of bits (ENOB)", "ADC의 실제 잡음·왜곡 성능을 이상적인 ADC의 비트 수로 환산한 값. (SINAD − 1.76) ÷ 6.02.", "rfchips"],
    ["안테나 인 패키지", "Antenna-in-package (AiP)", "안테나 배열을 RF 칩 패키지 기판에 함께 만든 모듈. 파장이 1 cm 안팎인 mmWave에서 칩과 안테나를 가깝게 붙여 손실을 줄인다.", "rfchips"],
    // 19 photonics
    ["광 트랜시버", "Optical transceiver", "전기 신호를 빛으로 바꿔 보내고 받은 빛을 다시 전기로 바꾸는 부품. 레이저·변조기·광검출기·TIA·DSP로 이루어지며 보통 플러그형 모듈로 만든다.", "photonics"],
    ["트랜스임피던스 증폭기", "Transimpedance amplifier (TIA)", "광검출기의 미세한 광전류를 전압으로 바꾸며 증폭하는 회로. 잡음이 수신 감도를 정한다.", "photonics"],
    ["유도 방출", "Stimulated emission", "들뜬 전자 옆을 지나는 광자가 같은 방향·파장·위상의 광자를 하나 더 만들어 내게 하는 현상. 레이저 증폭의 원리다.", "photonics"],
    ["문턱 전류", "Threshold current", "반도체 레이저에서 광 이득이 공진기 손실을 넘어 레이저 발진이 시작되는 전류. 온도가 오르면 커진다.", "photonics"],
    ["직접 밴드갭", "Direct bandgap", "전도대 최저점과 가전자대 최고점이 같은 운동량에 있는 반도체. 전자가 곧바로 빛을 내며 재결합해 레이저·LED 재료가 된다(GaAs, InP 등).", "photonics"],
    ["간접 밴드갭", "Indirect bandgap", "전도대 최저점과 가전자대 최고점의 운동량이 다른 반도체. 재결합에 포논이 필요해 빛을 거의 내지 못한다(Si, Ge).", "photonics"],
    ["VCSEL", "Vertical-cavity surface-emitting laser", "반사막 사이 얇은 활성층에서 칩 윗면으로 빛을 쏘는 레이저. 주로 850 nm GaAs 계열로 짧은 거리 다중 모드 링크에 쓴다.", "photonics"],
    ["DFB 레이저", "Distributed feedback laser", "활성층 옆에 새긴 주기적 격자로 한 파장만 되먹임하는 단일 파장 반도체 레이저. 1310/1550 nm 단일 모드 링크의 표준 광원.", "photonics"],
    ["EML", "Electro-absorption modulated laser", "DFB 레이저와 전계흡수 변조기(EAM)를 한 InP 칩에 집적한 광원. 고속에서도 파장 흔들림이 적다.", "photonics"],
    ["마하-젠더 변조기", "Mach-Zehnder modulator (MZM)", "빛을 두 갈래로 나눠 한쪽 위상을 전압으로 바꾼 뒤 다시 합쳐, 간섭으로 세기나 위상을 조절하는 외부 변조기. 출력은 cos²(Δφ/2)를 따른다.", "photonics"],
    ["광검출기", "Photodetector (PD)", "흡수한 광자로 전자-정공 쌍을 만들어 빛을 전류로 바꾸는 반도체 소자. PIN, APD, Ge-on-Si 등이 있다.", "photonics"],
    ["응답도", "Responsivity", "광검출기에 들어온 빛 1 W당 나오는 전류(A/W). η × λ(µm) / 1.24.", "photonics"],
    ["애벌랜치 포토다이오드", "Avalanche photodiode (APD)", "높은 역전압으로 전자를 가속해 충돌 이온화를 연쇄로 일으켜 내부에서 광전류를 증폭하는 광검출기.", "photonics"],
    ["실리콘 포토닉스", "Silicon photonics", "CMOS 공장의 실리콘(SOI) 웨이퍼에서 도파관·변조기·Ge 검출기 등 광 회로를 대량으로 만드는 기술. 레이저는 InP를 따로 붙인다.", "photonics"],
    ["링 공진기", "Ring resonator", "곧은 도파관 옆의 고리 도파관. 둘레가 파장의 정수배인 빛만 공진해 투과 스펙트럼에 골을 만들며, 굴절률을 바꿔 변조기·필터로 쓴다.", "photonics"],
    ["이종 집적", "Heterogeneous integration", "InP 같은 다른 재료의 박막이나 칩을 실리콘 웨이퍼에 접합해 함께 가공하는 방법. 실리콘 포토닉스에 레이저를 넣는 방법 중 하나다.", "photonics"],
    ["LPO", "Linear pluggable optics", "모듈 안의 DSP를 빼고 호스트 칩의 SerDes가 광 부품을 직접 선형 구동하는 플러그형 광 모듈. 전력과 지연이 줄어든다.", "photonics"],
    ["공동 패키징 광학", "Co-packaged optics (CPO)", "광 엔진을 스위치·가속기 칩과 같은 패키지 안에 붙여 전기 경로를 수 mm로 줄인 광 연결 방식. 비트당 에너지가 크게 준다.", "photonics"],
    ["광 회로 스위치", "Optical circuit switch (OCS)", "빛을 전기로 바꾸지 않고 MEMS 거울 등으로 그대로 다른 광섬유로 꺾어 연결을 바꾸는 스위치. 전력이 적지만 전환에 밀리초가 걸린다.", "photonics"],
    // 20 datacenter
    ["ToR 스위치", "Top of Rack switch", "서버 랙 맨 위에 두어 그 랙의 서버들을 모으는 스위치. 리프-스파인 구조에서 리프 역할을 한다.", "datacenter"],
    ["남북 트래픽", "North-south traffic", "데이터센터 바깥(사용자, 인터넷)과 안쪽 서버 사이를 오가는 트래픽.", "datacenter"],
    ["동서 트래픽", "East-west traffic", "데이터센터 안의 서버와 서버 사이를 오가는 트래픽. 분산 서비스와 AI 학습 때문에 남북 트래픽보다 훨씬 많다.", "datacenter"],
    ["리프-스파인", "Leaf-spine", "모든 리프(ToR) 스위치를 모든 스파인 스위치에 연결한 2단 Clos 구조. 어느 두 서버 사이든 같은 홉 수와 여러 개의 같은 길이 경로를 준다.", "datacenter"],
    ["래딕스", "Radix", "스위치 한 대가 가진 포트 수. 래딕스가 클수록 같은 단 수로 더 많은 서버를 연결할 수 있다.", "datacenter"],
    ["팻 트리", "Fat tree", "위로 올라가도 총 대역폭이 줄지 않게 만든 3단 Clos 구조. 포트 k개 스위치로 서버 k³/4대를 막힘 없이 잇는다.", "datacenter"],
    ["오버서브스크립션", "Oversubscription", "스위치의 아래쪽(서버 쪽) 대역폭과 위쪽 대역폭의 비. 3:1이면 모두가 동시에 보낼 때 1/3 속도만 낼 수 있다.", "datacenter"],
    ["이분 대역폭", "Bisection bandwidth", "네트워크의 노드를 절반씩 둘로 나눌 때, 두 무리 사이로 동시에 흐를 수 있는 최소(가장 나쁜 분할 기준) 대역폭.", "datacenter"],
    ["ECMP", "Equal-Cost Multi-Path", "길이가 같은 여러 경로에 트래픽을 나누는 라우팅. 보통 5-튜플 해시로 흐름 단위로 경로를 고른다.", "datacenter"],
    ["코끼리 흐름", "Elephant flow", "오래 지속되며 대용량을 나르는 소수의 흐름. 짧은 생쥐 흐름(mice flow)과 대비되며 ECMP 불균형의 주범이다.", "datacenter"],
    ["테일 지연", "Tail latency", "응답 시간 분포의 꼬리(p99, p99.9 등). 팬아웃 요청은 가장 느린 응답을 기다리므로 꼬리가 전체 속도를 좌우한다.", "datacenter"],
    ["인캐스트", "Incast", "많은 서버의 응답이 동시에 한 수신자에게 몰려 스위치 출구 버퍼가 넘치고 손실과 재전송 지연이 생기는 현상.", "datacenter"],
    ["RDMA", "Remote Direct Memory Access", "NIC가 상대 컴퓨터의 메모리를 CPU와 커널을 거치지 않고 직접 읽고 쓰는 기술. 지연이 µs 수준으로 줄어든다.", "datacenter"],
    ["InfiniBand", "InfiniBand", "고성능 컴퓨팅용으로 설계된 무손실 네트워크 기술. 크레딧 기반 흐름 제어와 RDMA를 기본으로 한다.", "datacenter"],
    ["RoCEv2", "RDMA over Converged Ethernet v2", "RDMA를 UDP/IP에 실어 이더넷 데이터센터망 위에서 쓰는 방식. 무손실에 가깝게 하려고 PFC와 ECN을 함께 쓴다.", "datacenter"],
    ["PFC", "Priority Flow Control", "버퍼가 차면 앞 장비에게 특정 우선순위 클래스의 전송을 잠시 멈추라고 알리는 이더넷 흐름 제어(IEEE 802.1Qbb).", "datacenter"],
    ["DCQCN", "Data Center Quantized Congestion Notification", "ECN 표시를 받으면 RDMA NIC가 하드웨어에서 송신 속도를 줄였다가 회복하는 혼잡 제어 방식.", "datacenter"],
    ["올리듀스", "All-reduce", "모든 참가자의 데이터를 더해(또는 다른 연산으로 합쳐) 그 결과를 모두가 나눠 갖는 집합 통신. 분산 AI 학습의 핵심 연산이다.", "datacenter"],
    ["스케일업과 스케일아웃", "Scale-up / Scale-out", "AI 클러스터에서 스케일업은 랙 안 GPU를 NVLink 같은 초고속 연결로 묶는 것, 스케일아웃은 서버·랙 사이를 이더넷/InfiniBand 백엔드망으로 잇는 것.", "datacenter"],
    ["레일 최적화", "Rail-optimized", "모든 서버의 같은 번호 GPU를 같은 레일 스위치에 연결하는 AI 클러스터 배선 방식. 집합 통신 트래픽이 한 홉에서 끝난다.", "datacenter"],
    // 21 cloud
    ["리전", "Region", "클라우드가 데이터센터를 묶어 운영하는 지리적 단위(예: 서울, 버지니아). 보통 가용 영역 3개 이상으로 이뤄진다.", "cloud"],
    ["가용 영역", "Availability Zone", "리전 안에서 전력·냉각·네트워크가 독립된 데이터센터 묶음. 서로 왕복 1~2 ms 수준으로 가까워 실시간 복제가 가능하다.", "cloud"],
    ["엣지 PoP", "Edge Point of Presence", "사용자 가까이에 둔 작은 거점. CDN 캐시, DNS, TLS 종료, DDoS 방어를 맡는다.", "cloud"],
    ["가상 스위치", "Virtual switch", "하이퍼바이저나 SmartNIC 안에서 VM·컨테이너의 가상 NIC를 물리 NIC와 잇는 소프트웨어 스위치. 예: Open vSwitch.", "cloud"],
    ["VPC", "Virtual Private Cloud", "클라우드 안에 만드는 고객 전용 가상 네트워크. 주소 범위, 서브넷, 라우팅 테이블, 게이트웨이, 방화벽 규칙을 직접 정한다.", "cloud"],
    ["인터넷 게이트웨이", "Internet Gateway", "VPC를 인터넷과 연결하는 출입구. 라우팅 테이블에 이 경로가 있는 서브넷이 퍼블릭 서브넷이다.", "cloud"],
    ["NAT 게이트웨이", "NAT Gateway", "프라이빗 서브넷의 서버가 바깥으로 나가는 연결만 허용하고, 바깥에서 먼저 들어오는 연결은 받지 않게 하는 관리형 NAT.", "cloud"],
    ["보안 그룹", "Security Group", "서버(가상 NIC) 단위로 붙는 상태 저장 방화벽. 허용 규칙만 있고, 허용된 요청의 응답은 자동으로 통과한다.", "cloud"],
    ["네트워크 ACL", "Network ACL", "서브넷 경계에 붙는 무상태 방화벽. 허용·거부 규칙을 번호순으로 평가하며, 응답 트래픽도 별도로 허용해야 한다.", "cloud"],
    ["오버레이", "Overlay network", "물리망(언더레이) 위에 캡슐화로 만든 가상 네트워크. 가상망 주소를 물리망과 분리한다.", "cloud"],
    ["VXLAN", "Virtual eXtensible LAN", "이더넷 프레임을 UDP(4789)/IP로 감싸는 오버레이 규약. 24비트 VNI로 약 1,677만 개 가상망을 구분하며, 헤더가 50바이트 늘어난다.", "cloud"],
    ["SDN", "Software-Defined Networking", "네트워크의 제어 평면을 장비에서 떼어 소프트웨어 컨트롤러로 모아 프로그램으로 관리하는 방식.", "cloud"],
    ["오픈플로우", "OpenFlow", "컨트롤러가 스위치의 ‘일치 → 동작’ 흐름 표를 원격으로 채우게 하는 SDN 표준 규약(2008년, 스탠퍼드).", "cloud"],
    ["로드 밸런서", "Load balancer", "하나의 주소로 들어온 요청을 여러 서버에 나눠 주는 장치·소프트웨어. L4(연결 단위)와 L7(HTTP 요청 단위)이 있다.", "cloud"],
    ["헬스 체크", "Health check", "로드 밸런서가 서버에 주기적으로 상태를 물어 응답이 없는 서버를 분배 대상에서 빼는 검사.", "cloud"],
    ["일관된 해싱", "Consistent hashing", "키와 노드를 해시 고리 위에 놓고 시계 방향으로 가장 가까운 노드에 배정하는 방식. 노드가 바뀌어도 키의 약 1/N만 옮겨 간다.", "cloud"],
    ["글로벌 로드 밸런싱", "Global Server Load Balancing", "DNS 등을 이용해 사용자 위치와 리전 상태에 따라 가장 적합한 리전으로 안내하는 전 지구 규모의 부하 분산.", "cloud"],
    ["이그레스", "Egress", "클라우드에서 바깥(인터넷, 다른 리전)으로 나가는 트래픽. 들어오는 트래픽과 달리 GB당 요금이 붙는 경우가 많다.", "cloud"],
    ["서비스 메시", "Service mesh", "마이크로서비스마다 사이드카 프록시를 붙여 서비스 간 통신의 재시도, 부하 분산, 관측, 상호 TLS를 처리하는 인프라 계층.", "cloud"],
    // 22 security
    ["기밀성", "Confidentiality", "허락받은 사람만 내용을 읽을 수 있는 성질. 암호화로 지킨다.", "security"],
    ["무결성", "Integrity", "데이터가 중간에 바뀌지 않았음을 보장하는 성질. 해시, 메시지 인증 코드, 디지털 서명으로 확인한다.", "security"],
    ["가용성", "Availability", "필요할 때 서비스를 쓸 수 있는 성질. DDoS 공격이 노리는 목표이며, 운영에서는 정상 동작 시간의 비율(예: 99.9%)로 잰다.", "security"],
    ["대칭키 암호", "Symmetric-key cipher", "암호화와 복호화에 같은 열쇠를 쓰는 암호. AES, ChaCha20이 대표이며 매우 빠르다.", "security"],
    ["공개키 암호", "Public-key cryptography", "공개키와 개인키 한 쌍을 쓰는 암호. 열쇠 교환과 디지털 서명에 쓴다. RSA, 타원곡선 암호(ECC)가 대표.", "security"],
    ["해시 함수", "Hash function", "임의 길이 데이터를 고정 길이 지문으로 바꾸는 함수. 거꾸로 되돌릴 수 없고, 입력이 조금만 바뀌어도 결과가 완전히 달라진다. 예: SHA-256.", "security"],
    ["메시지 인증 코드", "Message Authentication Code", "비밀 열쇠를 섞어 만든 짧은 검사값(MAC, HMAC). 열쇠를 아는 상대가 보냈고 내용이 바뀌지 않았음을 확인한다.", "security"],
    ["디피-헬먼 키 교환", "Diffie-Hellman key exchange", "공개 통로로 g^a, g^b만 주고받아 두 사람만 아는 비밀 g^ab를 만드는 방법. 이산 로그 문제의 어려움에 기댄다.", "security"],
    ["중간자 공격", "Man-in-the-middle attack", "통신 경로 한가운데서 양쪽에게 각각 상대인 척하며 내용을 엿보거나 바꾸는 공격. 인증서로 상대를 확인해 막는다.", "security"],
    ["TLS", "Transport Layer Security", "TCP나 QUIC 위에서 암호화·무결성·서버 인증을 제공하는 프로토콜. HTTPS의 S. TLS 1.3은 1-RTT로 연결한다.", "security"],
    ["인증서", "Certificate", "도메인 이름과 공개키를 묶고 인증 기관(CA)이 서명한 전자 문서(X.509). 브라우저는 루트까지 서명 체인을 따라 검증한다.", "security"],
    ["방화벽", "Firewall", "망 사이에서 규칙에 따라 패킷을 허용하거나 거부하는 장비·소프트웨어. 규칙은 보통 위에서부터 첫 일치로 적용한다.", "security"],
    ["VPN", "Virtual Private Network", "원래 패킷을 암호화해 새 IP 헤더로 감싸 보내는 터널. 공용 인터넷 위에 사설망처럼 쓰는 연결을 만든다. IPsec, WireGuard 등.", "security"],
    ["제로 트러스트", "Zero trust", "망 안쪽이라는 위치만으로 믿지 않고, 모든 요청마다 사용자·기기·권한을 확인하는 보안 원칙.", "security"],
    ["DDoS", "Distributed Denial of Service", "수많은 기기에서 동시에 트래픽을 퍼부어 서비스를 마비시키는 분산 서비스 거부 공격.", "security"],
    ["증폭 공격", "Amplification attack", "출발지를 피해자 주소로 위조한 작은 요청을 열린 서버에 보내, 훨씬 큰 응답이 피해자에게 쏟아지게 하는 반사형 DDoS.", "security"],
    ["SYN 쿠키", "SYN cookie", "SYN 플러드 방어 기법. 서버가 반쯤 열린 연결을 저장하지 않고, 연결 정보를 초기 순서 번호에 해시로 담아 보낸다.", "security"],
    ["이블 트윈", "Evil twin", "정상 Wi-Fi와 같은 이름으로 띄운 가짜 무선 공유기. 접속한 기기의 트래픽을 가로채거나 가짜 페이지를 보여 준다.", "security"],
    ["DNSSEC", "DNS Security Extensions", "DNS 레코드에 디지털 서명을 붙여 위조를 막는 확장. 무결성을 주지만 암호화는 하지 않는다.", "security"],
    ["포스트 양자 암호", "Post-quantum cryptography", "양자 컴퓨터로도 풀기 어려운 문제에 기반한 공개키 암호(PQC). 2024년 NIST가 ML-KEM 등을 표준화했다.", "security"],
    // 23 ops
    ["처리 지연", "Processing delay", "라우터가 헤더를 읽고 오류를 검사하고 내보낼 포트를 정하는 데 걸리는 시간. 전용 칩에서는 수 µs 이하.", "ops"],
    ["큐잉 지연", "Queuing delay", "나가는 포트 앞에서 먼저 온 패킷들이 나갈 때까지 줄 서서 기다리는 시간. 혼잡할수록 커지고 가장 변덕스럽다.", "ops"],
    ["전송 지연", "Transmission delay", "패킷의 모든 비트를 선로에 밀어 넣는 시간. 패킷 크기 ÷ 링크 속도.", "ops"],
    ["전파 지연", "Propagation delay", "신호가 선로를 따라 실제로 이동하는 시간. 거리 ÷ 전파 속도(광섬유에서 약 20만 km/s).", "ops"],
    ["패킷 손실", "Packet loss", "보낸 패킷 중 목적지에 닿지 못한 비율. 혼잡한 큐의 버림, 불량 링크, 약한 무선 신호가 주원인이다.", "ops"],
    ["대역폭-지연 곱", "Bandwidth-delay product", "대역폭 × RTT. 회선을 가득 채우려면 늘 길 위에 떠 있어야 하는 데이터 양(BDP)으로, 필요한 TCP 윈도우 크기를 정한다.", "ops"],
    ["큐잉 이론", "Queueing theory", "도착과 처리가 무작위인 대기열의 길이와 대기 시간을 다루는 수학. M/M/1 큐의 평균 체류 시간은 1/(μ − λ).", "ops"],
    ["버퍼블로트", "Bufferbloat", "장비의 버퍼가 너무 커서 TCP가 이를 가득 채워, 손실 대신 수백 ms의 큐잉 지연이 생기는 현상.", "ops"],
    ["AQM", "Active Queue Management", "큐가 가득 차기 전에 지연을 보고 패킷을 미리 버리거나 표시해 큐를 짧게 유지하는 방식. CoDel, FQ-CoDel이 대표.", "ops"],
    ["QoS", "Quality of Service", "트래픽을 분류해 우선순위·대역폭 비율·속도 제한 등으로 다르게 대우하는 기술의 묶음.", "ops"],
    ["DSCP", "Differentiated Services Code Point", "IP 헤더의 6비트 서비스 등급 필드. 예: 음성은 EF(46), 일반 트래픽은 0.", "ops"],
    ["토큰 버킷", "Token bucket", "속도 r로 토큰이 차고 최대 b개까지 담기는 통. 토큰이 있어야 패킷이 나가므로 평균 속도는 r, 순간 버스트는 b로 제한된다.", "ops"],
    ["패킷 캡처", "Packet capture", "네트워크 인터페이스를 지나는 패킷을 그대로 복사해 저장·분석하는 것. tcpdump, 와이어샤크가 대표 도구.", "ops"],
    ["SLO", "Service Level Objective", "서비스가 지켜야 할 내부 목표치. 예: 한 달간 요청의 99.9%가 300 ms 안에 성공. 남은 허용치가 오류 예산이다.", "ops"],
    ["백분위 지연", "Percentile latency", "지연을 크기순으로 늘어놓았을 때 p50(중앙값), p99(느린 쪽 1% 경계) 등의 값. 평균보다 체감 품질을 잘 보여 준다.", "ops"],
    // 24 journey
    ["시그널링", "Signaling", "통화를 시작하기 전에 서버를 거쳐 ‘누가 누구와, 어떤 코덱·암호 조건으로 통화할지’를 주고받는 약속 과정. 영상이 흐르는 미디어 경로와는 별개의 길이다.", "journey"],
    ["SDP", "Session Description Protocol", "통화 조건(쓸 수 있는 코덱, 해상도, 암호 인증서 지문, 주소 후보)을 적는 문서 형식. 제안(offer)과 응답(answer)을 맞춰 공통 조건을 정한다.", "journey"],
    ["WebRTC", "Web Real-Time Communication", "웹 브라우저와 앱에 내장된 실시간 음성·영상·데이터 통신 표준 묶음. ICE로 길을 찾고, DTLS로 열쇠를 나누고, SRTP로 미디어를 보낸다.", "journey"],
    ["STUN", "Session Traversal Utilities for NAT", "NAT 바깥의 서버가 ‘네 패킷은 이 공인 주소·포트에서 왔다’고 알려 주는 프로토콜. 직접 연결(P2P)에 쓸 내 바깥 주소를 알아내는 거울이다.", "journey"],
    ["TURN", "Traversal Using Relays around NAT", "직접 연결이 막힐 때 서버가 중계 주소를 빌려 주고 미디어 패킷을 받아 상대에게 넘겨 주는 방식. 항상 통하지만 경로가 늘고 서버 대역폭 비용이 든다.", "journey"],
    ["ICE", "Interactive Connectivity Establishment", "자기 주소, STUN으로 알아낸 바깥 주소, TURN 중계 주소 같은 후보를 서로 교환하고 짝마다 연결을 시험해 가장 좋은 길을 고르는 절차.", "journey"],
    ["RTP", "Real-time Transport Protocol", "실시간 음성·영상 조각에 순서 번호, 타임스탬프, 스트림 번호를 붙이는 12바이트 헤더 규칙. 보통 UDP 위에서 쓰고, 품질 보고는 짝인 RTCP가 맡는다.", "journey"],
    ["SRTP", "Secure RTP", "RTP의 내용을 암호화하고 인증 태그를 붙여 도청과 위조를 막는 방식. 열쇠는 통화를 맺을 때 DTLS 등으로 나눈다.", "journey"],
    ["지터 버퍼", "Jitter buffer", "들쭉날쭉하게 도착한 패킷을 잠깐 모았다가 고른 박자로 재생하는 대기실. 깊을수록 끊김은 줄지만 지연이 늘어난다.", "journey"],
    ["입-귀 지연", "Mouth-to-ear delay", "말한 소리가 상대 귀에 닿기까지의 한쪽 방향 전체 지연. ITU-T G.114는 150 ms 이하를 대부분의 대화에 적합한 수준으로 본다.", "journey"],
    ["패킷 손실 은닉", "Packet loss concealment, PLC", "끝내 받지 못한 음성·영상 조각을 앞뒤 정보로 그럴듯하게 메워 끊김을 덜 느끼게 하는 기법.", "journey"],
    ["SFU", "Selective Forwarding Unit", "그룹 통화에서 각자가 한 번 올린 영상을 받는 사람 화면에 맞는 화질로 골라 나눠 주는 서버. 다시 인코딩하지 않아 지연이 거의 늘지 않는다.", "journey"],
    // 25 history
    ["봉수", "Beacon relay (烽燧)", "산꼭대기 봉수대에서 밤에는 횃불, 낮에는 연기로 신호를 이어 전하던 조선의 군사 통신망. 횃불 개수 1~5개로 다섯 가지 상황을 알렸다.", "history"],
    ["광학 전신", "Semaphore telegraph", "1790년대 프랑스의 샤프가 만든 통신망. 탑 꼭대기 막대 팔의 각도로 기호를 만들고 다음 탑이 망원경으로 보고 따라 했다.", "history"],
    ["모스 부호", "Morse code", "점(짧은 신호)과 선(긴 신호)의 조합으로 글자를 나타내는 부호. 자주 쓰는 글자일수록 짧은 부호를 받는다.", "history"],
    ["패킷 교환", "Packet switching", "데이터를 작은 패킷으로 나눠 회선을 예약하지 않고 여러 사용자가 길을 함께 쓰며 보내는 방식. 배런, 데이비스, 클라인록이 1960년대에 기초를 놓았다.", "history"],
    ["아파넷", "ARPANET", "1969년 미국 ARPA가 만든 최초의 대규모 패킷 교환망. 1983년 TCP/IP로 전환하며 인터넷의 뿌리가 되었다.", "history"],
    ["닐슨의 법칙", "Nielsen's law", "고급 사용자의 가정용 인터넷 회선 속도가 매년 약 50%씩 빨라진다는 경험 법칙. 10년에 약 58배다.", "history"],
    ["IETF", "Internet Engineering Task Force", "인터넷 프로토콜 표준을 만드는 열린 모임. 누구나 참여하며 거친 합의와 실제로 돌아가는 코드를 중시하고, 결과를 RFC로 낸다.", "history"],
    ["ICANN", "Internet Corporation for Assigned Names and Numbers", "도메인 이름 체계의 최상위와 IP 주소 할당의 꼭대기를 조정하는 비영리 국제 기구. 1998년 설립되었다.", "history"],
    ["양자 키 분배", "QKD (Quantum Key Distribution)", "광자 같은 양자 상태에 비트를 실어 암호 키를 나누는 방법. 도청하면 양자 상태가 바뀌어 흔적이 남는다.", "history"],
    ["가시광 통신", "VLC (Visible Light Communication)", "LED 조명을 눈에 보이지 않을 만큼 빠르게 깜빡여 데이터를 보내는 무선 통신. Li-Fi라고도 하며 IEEE 802.11bb로 표준화되었다.", "history"],
    ["지연 내성 네트워크", "DTN (Delay/Disruption Tolerant Networking)", "지연이 매우 길고 연결이 자주 끊기는 환경을 위한 네트워크. 중간 노드가 데이터 묶음(번들)을 저장했다가 길이 열리면 전달한다.", "history"],
    ["통계적 다중화", "Statistical multiplexing", "사용자들이 늘 동시에 보내지는 않는다는 점을 이용해, 회선을 예약하지 않고 함께 써서 더 많은 사용자를 수용하는 방식.", "history"],
    ["서브테라헤르츠", "Sub-terahertz", "약 100~300 GHz의 주파수 대역. 매우 넓은 대역폭을 쓸 수 있어 6G 후보로 연구되지만 거리와 장애물에 약하다.", "history"],
    ["양자 내성 암호", "PQC (Post-Quantum Cryptography)", "양자 컴퓨터로도 풀기 어려운 수학 문제에 기반한 암호. 미국 NIST가 2024년 첫 표준을 발표했다.", "history"],
];

/* 본문 표기 → 용어집 표제어 (툴팁 연결용) */
window.NB_TERM_ALIAS = {
  "심볼": "보",
  "WDM": "파장 분할 다중화",
  "MAC 주소 학습": "MAC 주소 테이블",
  "802.1Q tag": "VLAN 태그",
  "ABR": "적응형 비트레이트",
  "Clos 네트워크": "리프-스파인",
  "링 올리듀스": "올리듀스",
  "스케일업": "스케일업과 스케일아웃",
  "스케일아웃": "스케일업과 스케일아웃",
  "언더레이": "오버레이",
  "GSLB": "글로벌 로드 밸런싱"
};
