    ["RF 프런트엔드", "RF front-end (RFFE)", "안테나 바로 뒤에서 안테나 스위치·튜너, 대역별 필터와 듀플렉서, 전력 증폭기, 저잡음 증폭기를 묶은 부분. 휴대폰에서는 여러 재료의 칩을 한 모듈에 넣는다.", "rfchips"],
    ["믹서", "Mixer", "두 신호를 곱해 합·차 주파수를 만드는 회로. 수신 신호를 국부 발진기와 곱해 낮은 주파수로 내리거나, 송신 신호를 높은 주파수로 올린다.", "rfchips"],
    ["국부 발진기", "Local oscillator (LO)", "믹서에 곱해 주는 깨끗한 기준 사인파. 보통 PLL로 만들며, 주파수를 바꿔 원하는 채널을 고른다.", "rfchips"],
    ["중간 주파수", "Intermediate frequency (IF)", "슈퍼헤테로다인 수신기에서 수신 주파수와 LO 주파수의 차로 얻는 고정된 중간 단계 주파수. 여기서 날카로운 필터로 이웃 신호를 걷어 낸다.", "rfchips"],
    ["이미지 주파수", "Image frequency", "LO를 사이에 두고 원하는 신호와 거울 대칭인 주파수(2·f_LO − f_RF). 믹서를 거치면 원하는 신호와 같은 IF로 내려와 겹치므로 믹서 앞에서 걸러야 한다.", "rfchips"],
    ["직접 변환 수신기", "Direct-conversion (zero-IF) receiver", "LO를 신호 주파수와 같게 놓아 곧장 0 Hz 근처로 내리는 수신기. 90° 어긋난 두 LO로 I와 Q를 얻으며, 오늘날 휴대폰 트랜시버의 기본 구조다.", "rfchips"],
    ["전압 제어 발진기", "Voltage-controlled oscillator (VCO)", "입력 전압에 따라 출력 주파수가 바뀌는 발진기. 주파수를 넓게 바꿀 수 있지만 혼자서는 불안정해 PLL로 묶어 쓴다.", "rfchips"],
    ["위상 고정 루프", "Phase-locked loop (PLL)", "VCO 출력을 N으로 나눈 신호를 수정 발진기와 계속 비교해 VCO를 고정하는 되먹임 회로. 출력 주파수는 N × 기준 주파수가 된다.", "rfchips"],
    ["위상 잡음", "Phase noise", "발진기 출력의 위상이 무작위로 흔들리는 현상. 스펙트럼에서는 반송파 옆의 치마로, 성좌도에서는 점들이 원 방향으로 번지는 모습으로 나타난다. 단위 dBc/Hz.", "rfchips"],
    ["전력 증폭기", "Power amplifier (PA)", "송신 신호를 안테나로 내보낼 만큼 크게 키우는 증폭기. 휴대폰 PA는 주로 GaAs HBT, 기지국 PA는 GaN HEMT로 만든다.", "rfchips"],
    ["전력 부가 효율", "Power-added efficiency (PAE)", "(출력 RF 전력 − 입력 RF 전력) ÷ 공급 직류 전력. PA가 배터리 전력을 얼마나 전파로 바꾸는지 나타낸다.", "rfchips"],
    ["백오프", "Back-off", "신호의 순간 봉우리가 찌그러지지 않도록 PA의 평균 출력을 포화점보다 낮춰 쓰는 정도(dB). 크게 하면 선형성은 좋아지고 효율은 떨어진다.", "rfchips"],
    ["포락선 추적", "Envelope tracking (ET)", "신호 크기(포락선)에 맞춰 PA의 공급 전압을 실시간으로 오르내려 효율을 높이는 기술.", "rfchips"],
    ["디지털 전치 왜곡", "Digital pre-distortion (DPD)", "PA의 비선형 왜곡을 미리 측정해 디지털 단계에서 반대로 찌그러뜨려 보내 상쇄하는 기술. 백오프를 줄여 효율을 높인다.", "rfchips"],
    ["잡음 지수", "Noise figure (NF)", "회로를 통과하며 신호 대 잡음비가 몇 dB 나빠지는지 나타내는 값. 여러 단의 전체 값은 프리스 공식으로 계산한다.", "rfchips"],
    ["저잡음 증폭기", "Low-noise amplifier (LNA)", "수신 경로의 첫 단에서 자신의 잡음을 최소로 보태며 약한 신호를 키우는 증폭기. 전체 잡음 지수를 사실상 결정한다.", "rfchips"],
    ["수신 감도", "Receiver sensitivity", "수신기가 정해진 품질로 알아들을 수 있는 가장 약한 신호 세기. −174 dBm/Hz + 10·log(대역폭) + NF + 필요 SNR.", "rfchips"],
    ["듀플렉서", "Duplexer", "송신 필터와 수신 필터를 하나로 묶어, 한 안테나로 서로 다른 주파수에서 동시에 송수신하게 하는 부품(FDD).", "rfchips"],
    ["SAW 필터", "Surface acoustic wave filter", "압전 기판 표면의 빗살 전극으로 전기 신호를 표면 음파로 바꿔 거르는 필터. 싸고 성숙했으며 주로 약 2.5 GHz 이하에 쓴다.", "rfchips"],
    ["BAW 필터", "Bulk acoustic wave filter", "AlN 같은 압전 박막을 두께 방향으로 공진시켜 거르는 필터. Q가 높고 6 GHz 근처까지 쓸 수 있다. FBAR와 SMR이 대표 구조다.", "rfchips"],
    ["RF-SOI", "RF silicon-on-insulator", "얇은 산화막 위에 실리콘 소자를 만든 RF용 웨이퍼 공정. 기판 손실과 기생 용량이 작아 안테나 스위치·튜너·LNA에 널리 쓴다.", "rfchips"],
    ["유효 비트 수", "Effective number of bits (ENOB)", "ADC의 실제 잡음·왜곡 성능을 이상적인 ADC의 비트 수로 환산한 값. (SINAD − 1.76) ÷ 6.02.", "rfchips"],
    ["안테나 인 패키지", "Antenna-in-package (AiP)", "안테나 배열을 RF 칩 패키지 기판에 함께 만든 모듈. 파장이 1 cm 안팎인 mmWave에서 칩과 안테나를 가깝게 붙여 손실을 줄인다.", "rfchips"],
