    ["액세스 포인트", "Access Point (AP)", "무선 단말과 유선 이더넷 사이를 이어 주는 장비. Wi-Fi 프레임을 이더넷 프레임으로 바꿔 넘긴다. 공유기 안에도 들어 있다.", "wifi"],
    ["비컨", "Beacon", "AP가 약 0.1초(102.4 ms)마다 방송하는 안내 프레임. SSID, 지원 속도, 보안 방식, 채널 정보를 담는다.", "wifi"],
    ["SSID", "Service Set Identifier", "Wi-Fi 네트워크의 이름. 비컨에 실려 방송되며 휴대폰 Wi-Fi 목록에 보이는 이름이 이것이다.", "wifi"],
    ["4-way 핸드셰이크", "4-way handshake", "WPA2/WPA3에서 AP와 단말이 난수 두 개를 주고받아 이번 연결에만 쓸 암호 키를 각자 계산하는 4단계 교환. 비밀번호는 전파로 나가지 않는다.", "wifi"],
    ["채널 본딩", "Channel bonding", "이웃한 20 MHz 채널을 묶어 40·80·160·320 MHz의 넓은 채널로 쓰는 것. 속도는 늘지만 쓸 수 있는 채널 수는 준다.", "wifi"],
    ["CSMA/CA", "Carrier Sense Multiple Access with Collision Avoidance", "먼저 채널을 듣고, 조용하면 무작위 백오프만큼 기다린 뒤 보내며, ACK로 성공을 확인하는 Wi-Fi의 매체 접근 규칙.", "wifi"],
    ["백오프", "Backoff", "충돌을 피하려고 0~CW 사이의 무작위 슬롯 수만큼 기다리는 것. 충돌할 때마다 CW를 두 배로 늘린다(지수 백오프).", "wifi"],
    ["숨은 노드 문제", "Hidden node problem", "두 단말이 AP에는 닿지만 서로의 신호는 듣지 못해, 동시에 보내 AP에서 충돌하는 문제. RTS/CTS로 완화한다.", "wifi"],
    ["RTS/CTS", "Request to Send / Clear to Send", "긴 프레임을 보내기 전 짧은 예약 요청(RTS)과 허가(CTS)를 주고받아, 숨은 단말까지 그 시간 동안 침묵(NAV)하게 하는 방식.", "wifi"],
    ["프레임 집적", "Frame aggregation (A-MPDU)", "여러 프레임을 한 번의 전송에 묶어 보내 프리앰블·대기·ACK 같은 고정 오버헤드를 나눠 갖게 하는 기법. 실제 속도의 핵심.", "wifi"],
    ["메시 Wi-Fi", "Mesh Wi-Fi", "여러 AP 노드가 같은 SSID를 내보내고 서로 무선·유선으로 이어져 하나의 망처럼 집 전체를 덮는 방식.", "wifi"],
    ["로밍", "Roaming", "단말이 연결을 유지한 채 한 AP에서 다른 AP로 옮겨 가는 것. Wi-Fi에서는 단말이 결정하며 802.11k/v/r이 돕는다.", "wifi"],
    ["OFDMA", "Orthogonal Frequency Division Multiple Access", "OFDM의 부반송파를 묶음(자원 단위)으로 나눠 한 번의 전송에서 여러 사용자에게 동시에 배정하는 다중 접속 방식. Wi-Fi 6, LTE, 5G가 쓴다.", "wifi"],
    ["TWT", "Target Wake Time", "AP와 단말이 다음에 깨어날 시각을 약속해, 그 사이 단말이 무선부를 꺼 두도록 하는 Wi-Fi 6의 절전 기능.", "wifi"],
    ["MLO", "Multi-Link Operation", "Wi-Fi 7에서 한 연결이 2.4·5·6 GHz 등 여러 대역의 링크를 동시에 쓰는 기능. 속도를 더하고 지연을 줄인다.", "wifi"],
    ["주파수 도약", "Frequency hopping", "짧은 시간마다 정해진 순서로 채널을 바꿔 가며 통신해 간섭과 도청을 피하는 방식. 클래식 블루투스는 79개 채널을 초당 1,600번 옮긴다.", "wifi"],
    ["BLE", "Bluetooth Low Energy", "대부분의 시간을 잠자고 수 ms만 깨어나 보내는 저전력 블루투스. 2 MHz 채널 40개를 쓰며 코인 전지로 수년 동작한다.", "wifi"],
    ["Matter", "Matter", "제조사가 달라도 스마트홈 기기를 같은 방식으로 제어하게 하는 응용 계층 표준. Wi-Fi·Thread·이더넷 위에서 동작한다.", "wifi"],
    ["LoRa", "Long Range", "1 GHz 아래 비면허 대역에서 신호를 넓게 확산해 수 km를 수 kbps로, 배터리 수년으로 보내는 저전력 장거리 무선 방식.", "wifi"],
