    ["봉수", "Beacon relay (烽燧)", "산꼭대기 봉수대에서 밤에는 횃불, 낮에는 연기로 신호를 이어 전하던 조선의 군사 통신망. 횃불 개수 1~5개로 다섯 가지 상황을 알렸다.", "history"],
    ["광학 전신", "Semaphore telegraph", "1790년대 프랑스의 샤프가 만든 통신망. 탑 꼭대기 막대 팔의 각도로 기호를 만들고 다음 탑이 망원경으로 보고 따라 했다.", "history"],
    ["모스 부호", "Morse code", "점(짧은 신호)과 선(긴 신호)의 조합으로 글자를 나타내는 부호. 자주 쓰는 글자일수록 짧은 부호를 받는다.", "history"],
    ["패킷 교환", "Packet switching", "데이터를 작은 패킷으로 나눠 회선을 예약하지 않고 여러 사용자가 길을 함께 쓰며 보내는 방식. 배런, 데이비스, 클라인록이 1960년대에 기초를 놓았다.", "history"],
    ["아파넷", "ARPANET", "1969년 미국 ARPA가 만든 최초의 대규모 패킷 교환망. 1983년 TCP/IP로 전환하며 인터넷의 뿌리가 되었다.", "history"],
    ["닐슨의 법칙", "Nielsen's law", "고급 사용자의 가정용 인터넷 회선 속도가 매년 약 50%씩 빨라진다는 경험 법칙. 10년에 약 58배다.", "history"],
    ["IETF", "Internet Engineering Task Force", "인터넷 프로토콜 표준을 만드는 열린 모임. 누구나 참여하며 거친 합의와 실제로 돌아가는 코드를 중시하고, 결과를 RFC로 낸다.", "history"],
    ["ICANN", "Internet Corporation for Assigned Names and Numbers", "도메인 이름 체계의 최상위와 IP 주소 할당의 꼭대기를 조정하는 비영리 국제 기구. 1998년 설립되었다.", "history"],
    ["양자 키 분배", "QKD (Quantum Key Distribution)", "광자 같은 양자 상태에 비트를 실어 암호 키를 나누는 방법. 도청하면 양자 상태가 바뀌어 흔적이 남는다.", "history"],
    ["가시광 통신", "VLC (Visible Light Communication)", "LED 조명을 눈에 보이지 않을 만큼 빠르게 깜빡여 데이터를 보내는 무선 통신. Li-Fi라고도 하며 IEEE 802.11bb로 표준화되었다.", "history"],
    ["지연 내성 네트워크", "DTN (Delay/Disruption Tolerant Networking)", "지연이 매우 길고 연결이 자주 끊기는 환경을 위한 네트워크. 중간 노드가 데이터 묶음(번들)을 저장했다가 길이 열리면 전달한다.", "history"],
    ["통계적 다중화", "Statistical multiplexing", "사용자들이 늘 동시에 보내지는 않는다는 점을 이용해, 회선을 예약하지 않고 함께 써서 더 많은 사용자를 수용하는 방식.", "history"],
    ["서브테라헤르츠", "Sub-terahertz", "약 100~300 GHz의 주파수 대역. 매우 넓은 대역폭을 쓸 수 있어 6G 후보로 연구되지만 거리와 장애물에 약하다.", "history"],
    ["양자 내성 암호", "PQC (Post-Quantum Cryptography)", "양자 컴퓨터로도 풀기 어려운 수학 문제에 기반한 암호. 미국 NIST가 2024년 첫 표준을 발표했다.", "history"],
