    ["포트 번호", "Port Number", "한 컴퓨터 안에서 데이터를 받을 앱을 가리키는 0~65535의 16비트 번호. IP 주소가 건물이라면 포트는 호수다.", "tcp"],
    ["잘 알려진 포트", "Well-known Ports", "0~1023번 포트. HTTPS 443, DNS 53, SSH 22처럼 대표 서비스에 미리 정해진 번호다.", "tcp"],
    ["소켓", "Socket", "IP 주소와 포트 번호의 쌍, 또는 프로그램이 네트워크와 데이터를 주고받는 창구. TCP 연결은 양쪽 소켓과 프로토콜의 5-튜플로 구분된다.", "tcp"],
    ["UDP", "User Datagram Protocol", "8바이트 헤더만 붙여 연결·확인·재전송 없이 그냥 보내는 전송 프로토콜. DNS, 게임, 음성·영상 통화, QUIC의 바탕이 된다.", "tcp"],
    ["TCP", "Transmission Control Protocol", "연결을 맺고 순서 번호·확인 응답·재전송·흐름 제어·혼잡 제어로 바이트 흐름을 빠짐없이 순서대로 전달하는 전송 프로토콜.", "tcp"],
    ["3방향 핸드셰이크", "Three-way Handshake", "SYN → SYN-ACK → ACK 세 번의 교환으로 양쪽이 서로의 시작 순서 번호를 확인하고 TCP 연결을 여는 절차.", "tcp"],
    ["순서 번호", "Sequence Number", "TCP 세그먼트에 담긴 첫 바이트가 전체 바이트 흐름에서 몇 번째인지 나타내는 32비트 번호. 패킷이 아니라 바이트 단위다.", "tcp"],
    ["누적 ACK", "Cumulative ACK", "“이 번호 앞까지는 빈틈없이 다 받았다”를 알리는 확인 응답. 중간이 빠지면 같은 ACK 번호가 반복된다.", "tcp"],
    ["재전송 타임아웃", "Retransmission Timeout", "보낸 데이터의 ACK를 기다리는 제한 시간(RTO). 측정한 RTT로 계산하며, 넘으면 손실로 보고 다시 보낸다.", "tcp"],
    ["빠른 재전송", "Fast Retransmit", "같은 ACK 번호가 세 번 더(중복 ACK 3개) 오면 타임아웃을 기다리지 않고 빠진 세그먼트를 곧바로 다시 보내는 기법.", "tcp"],
    ["슬라이딩 윈도우", "Sliding Window", "확인을 받기 전에 연달아 보낼 수 있는 데이터의 범위. ACK가 오면 창이 앞으로 미끄러진다. 처리율 ≤ 윈도우/RTT.", "tcp"],
    ["흐름 제어", "Flow Control", "받는 쪽이 알려 주는 수신 윈도우(rwnd)만큼만 보내 수신 버퍼가 넘치지 않게 하는 TCP 기능.", "tcp"],
    ["혼잡 제어", "Congestion Control", "보내는 쪽이 손실·지연을 보고 네트워크 병목이 감당할 양을 추정해 전송 속도를 조절하는 기능.", "tcp"],
    ["혼잡 윈도우", "Congestion Window", "혼잡 제어를 위해 보내는 쪽이 스스로 관리하는 전송 한도(cwnd). 실제 전송량은 min(cwnd, rwnd)다.", "tcp"],
    ["슬로 스타트", "Slow Start", "작은 cwnd에서 시작해 RTT마다 두 배로 늘리는 TCP의 시작 단계. ssthresh에 닿으면 혼잡 회피로 넘어간다.", "tcp"],
    ["AIMD", "Additive Increase Multiplicative Decrease", "손실이 없으면 조금씩 더하고, 손실이 나면 곱으로 크게 줄이는 규칙. cwnd의 톱니 모양과 흐름 간 공평한 분배를 만든다.", "tcp"],
    ["CUBIC", "CUBIC", "마지막 손실 때의 윈도우 크기를 기준으로 3차 함수 모양으로 cwnd를 늘리는 혼잡 제어. 리눅스·윈도우·macOS의 기본값.", "tcp"],
    ["BBR", "Bottleneck Bandwidth and RTT", "손실 대신 병목 대역폭과 최소 RTT를 측정해 그 곱(BDP)만큼만 보내는 구글의 혼잡 제어 알고리즘.", "tcp"],
    ["헤드 오브 라인 블로킹", "Head-of-Line Blocking", "맨 앞의 데이터 하나가 늦어 그 뒤의 데이터까지 모두 기다리게 되는 현상. TCP 위 HTTP/2에서 패킷 하나의 손실이 모든 스트림을 멈추게 한다.", "tcp"],
    ["QUIC", "QUIC", "UDP 위에서 동작하며 TLS 1.3을 내장한 전송 프로토콜(RFC 9000). 1-RTT/0-RTT 연결, 독립 스트림, 연결 ID에 의한 연결 이전을 제공한다. HTTP/3의 바탕.", "tcp"],
