    ["시그널링", "Signaling", "통화를 시작하기 전에 서버를 거쳐 ‘누가 누구와, 어떤 코덱·암호 조건으로 통화할지’를 주고받는 약속 과정. 영상이 흐르는 미디어 경로와는 별개의 길이다.", "journey"],
    ["SDP", "Session Description Protocol", "통화 조건(쓸 수 있는 코덱, 해상도, 암호 인증서 지문, 주소 후보)을 적는 문서 형식. 제안(offer)과 응답(answer)을 맞춰 공통 조건을 정한다.", "journey"],
    ["WebRTC", "Web Real-Time Communication", "웹 브라우저와 앱에 내장된 실시간 음성·영상·데이터 통신 표준 묶음. ICE로 길을 찾고, DTLS로 열쇠를 나누고, SRTP로 미디어를 보낸다.", "journey"],
    ["STUN", "Session Traversal Utilities for NAT", "NAT 바깥의 서버가 ‘네 패킷은 이 공인 주소·포트에서 왔다’고 알려 주는 프로토콜. 직접 연결(P2P)에 쓸 내 바깥 주소를 알아내는 거울이다.", "journey"],
    ["TURN", "Traversal Using Relays around NAT", "직접 연결이 막힐 때 서버가 중계 주소를 빌려 주고 미디어 패킷을 받아 상대에게 넘겨 주는 방식. 항상 통하지만 경로가 늘고 서버 대역폭 비용이 든다.", "journey"],
    ["ICE", "Interactive Connectivity Establishment", "자기 주소, STUN으로 알아낸 바깥 주소, TURN 중계 주소 같은 후보를 서로 교환하고 짝마다 연결을 시험해 가장 좋은 길을 고르는 절차.", "journey"],
    ["RTP", "Real-time Transport Protocol", "실시간 음성·영상 조각에 순서 번호, 타임스탬프, 스트림 번호를 붙이는 12바이트 헤더 규칙. 보통 UDP 위에서 쓰고, 품질 보고는 짝인 RTCP가 맡는다.", "journey"],
    ["SRTP", "Secure RTP", "RTP의 내용을 암호화하고 인증 태그를 붙여 도청과 위조를 막는 방식. 열쇠는 통화를 맺을 때 DTLS 등으로 나눈다.", "journey"],
    ["지터 버퍼", "Jitter buffer", "들쭉날쭉하게 도착한 패킷을 잠깐 모았다가 고른 박자로 재생하는 대기실. 깊을수록 끊김은 줄지만 지연이 늘어난다.", "journey"],
    ["입-귀 지연", "Mouth-to-ear delay", "말한 소리가 상대 귀에 닿기까지의 한쪽 방향 전체 지연. ITU-T G.114는 150 ms 이하를 대부분의 대화에 적합한 수준으로 본다.", "journey"],
    ["패킷 손실 은닉", "Packet loss concealment, PLC", "끝내 받지 못한 음성·영상 조각을 앞뒤 정보로 그럴듯하게 메워 끊김을 덜 느끼게 하는 기법.", "journey"],
    ["SFU", "Selective Forwarding Unit", "그룹 통화에서 각자가 한 번 올린 영상을 받는 사람 화면에 맞는 화질로 골라 나눠 주는 서버. 다시 인코딩하지 않아 지연이 거의 늘지 않는다.", "journey"],
