    ["최선형 전달", "best-effort delivery", "배달을 위해 노력하지만 분실·순서 뒤바뀜·중복을 막아 주지 않는 방식. 신뢰성은 TCP 같은 위 계층이 맡는다.", "ip"],
    ["CIDR", "Classless Inter-Domain Routing", "주소 뒤에 /n을 붙여 네트워크 부분의 비트 수를 자유롭게 정하는 방식. 1993년 고정 클래스를 대체했다.", "ip"],
    ["프리픽스 길이", "prefix length", "IP 주소에서 앞쪽 몇 비트가 네트워크 부분인지 나타내는 수. 192.168.0.0/24의 24.", "ip"],
    ["서브넷 마스크", "subnet mask", "네트워크 비트 자리는 1, 호스트 비트 자리는 0인 32비트 값. /24는 255.255.255.0이다.", "ip"],
    ["서브넷", "subnet", "하나의 IP 주소 블록을 프리픽스를 늘려 나눈 작은 네트워크. 같은 서브넷끼리는 라우터 없이 직접 통신한다.", "ip"],
    ["브로드캐스트 주소", "broadcast address", "호스트 비트가 모두 1인 주소. 그 서브넷의 모든 기기에게 보낼 때 쓰며 기기에게 배정할 수 없다.", "ip"],
    ["VLSM", "Variable Length Subnet Mask", "서브넷마다 프리픽스 길이를 다르게 해서 필요한 크기만큼 주소를 나눠 주는 방법.", "ip"],
    ["사설 IP 주소", "private address", "10/8, 172.16/12, 192.168/16처럼 내부망에서 자유롭게 쓰지만 인터넷으로는 직접 나갈 수 없는 주소(RFC 1918).", "ip"],
    ["루프백", "loopback", "자기 자신을 가리키는 주소(127.0.0.1, IPv6는 ::1). 보낸 패킷이 밖으로 나가지 않고 되돌아온다.", "ip"],
    ["DHCP", "Dynamic Host Configuration Protocol", "새 기기에게 IP 주소·마스크·게이트웨이·DNS를 일정 기간 임대해 주는 프로토콜. Discover·Offer·Request·ACK(DORA)로 진행된다.", "ip"],
    ["ARP", "Address Resolution Protocol", "같은 LAN에서 IP 주소에 해당하는 MAC 주소를 브로드캐스트로 물어 알아내는 프로토콜.", "ip"],
    ["NAT", "Network Address Translation", "패킷의 IP 주소를 바꿔 적는 기술. 공유기는 사설 주소를 공인 주소 하나로 바꿔 내보낸다.", "ip"],
    ["PAT", "Port Address Translation", "주소와 함께 포트 번호까지 바꿔, 공인 IP 하나를 여러 기기가 동시에 쓰게 하는 NAT. NAPT라고도 한다.", "ip"],
    ["포트 포워딩", "port forwarding", "공인 주소의 특정 포트로 들어온 연결을 내부의 정해진 기기·포트로 넘기도록 공유기에 넣는 고정 규칙.", "ip"],
    ["CGNAT", "Carrier-Grade NAT", "통신사 장비에서 하는 대규모 NAT. 여러 가입자가 공인 IP 하나를 나눠 쓴다.", "ip"],
    ["IPv6", "Internet Protocol version 6", "128비트 주소(약 3.4×10^38개)를 쓰는 차세대 IP. 16진수 8묶음을 콜론으로 잇고 ::로 축약한다.", "ip"],
    ["SLAAC", "Stateless Address Autoconfiguration", "IPv6 기기가 라우터 광고의 프리픽스에 스스로 정한 인터페이스 ID를 붙여 주소를 만드는 방법.", "ip"],
    ["듀얼 스택", "dual stack", "기기와 망이 IPv4와 IPv6를 동시에 쓰는 과도기 운영 방식.", "ip"],
    ["단편화", "fragmentation", "MTU보다 큰 IPv4 패킷을 여러 조각으로 나눠 보내는 것. 재조립은 목적지가 한다.", "ip"],
    ["TTL", "Time To Live", "IP 헤더의 남은 홉 수. 라우터마다 1씩 줄고 0이 되면 버려져 라우팅 고리에서 패킷이 영원히 도는 것을 막는다.", "ip"],
