    ["SerDes", "Serializer/Deserializer", "병렬 데이터를 한 줄로 늘어세워 고속으로 보내고(직렬화), 받은 쪽에서 다시 병렬로 펼치는(역직렬화) 회로. 오늘날에는 등화·클럭 복원·FEC까지 포함한 고속 송수신기 전체를 가리킨다.", "serdes"],
    ["스큐", "Skew", "같은 순간 출발한 신호들이 선 길이·환경 차이 때문에 서로 다른 시각에 도착하는 어긋남.", "serdes"],
    ["차동 신호", "Differential signaling", "두 선에 서로 반대 극성의 신호를 실어 보내고 그 차이로 값을 읽는 방식. 두 선에 똑같이 실린 외부 잡음은 빼면 사라진다.", "serdes"],
    ["레인", "Lane", "고속 직렬 링크의 기본 단위. 송신용 차동 쌍 하나와 수신용 차동 쌍 하나로 이루어진다. 포트 속도 = 레인 수 × 레인 속도.", "serdes"],
    ["보 레이트", "Baud rate", "1초에 보내는 기호(심볼)의 수. 단위는 Bd. 비트 레이트 = 보 레이트 × 기호당 비트 수.", "serdes"],
    ["NRZ", "Non-Return-to-Zero", "전압 2단계로 기호당 1비트를 보내는 가장 단순한 선로 부호. 25G 레인까지의 주류였다.", "serdes"],
    ["PAM4", "4-level Pulse Amplitude Modulation", "전압 4단계로 기호당 2비트를 보내는 방식. 같은 보 레이트에 두 배의 비트를 싣지만 눈 높이가 1/3로 줄어 약 9.5 dB 잡음에 약해진다.", "serdes"],
    ["나이퀴스트 주파수", "Nyquist frequency", "보 레이트의 절반. 신호가 가장 빠르게 바뀔 때의 기본 주파수로, 채널 손실을 이 주파수에서 따진다.", "serdes"],
    ["삽입 손실", "Insertion loss", "신호가 채널(배선·커넥터·케이블)을 지나며 잃는 세기를 dB로 나타낸 값. 주파수가 높을수록 커진다.", "serdes"],
    ["심볼 간 간섭", "ISI, Inter-Symbol Interference", "채널을 지나며 퍼진 펄스의 꼬리가 이웃 비트 자리에 겹쳐 값을 헷갈리게 만드는 현상.", "serdes"],
    ["이퀄라이저", "Equalizer", "채널이 깎아 먹은 고주파를 되살리거나 ISI를 빼 주어 닫힌 눈을 다시 여는 회로. FFE·CTLE·DFE가 대표적이다.", "serdes"],
    ["FFE", "Feed-Forward Equalizer", "현재 비트에 앞뒤 비트를 일정 비율 빼서 섞는 유한 탭 필터. 송신 쪽(디엠퍼시스)과 수신 DSP에 쓰인다.", "serdes"],
    ["CTLE", "Continuous-Time Linear Equalizer", "수신 입구의 아날로그 필터로 저주파를 깎아 고주파를 상대적으로 키운다. 잡음도 함께 키우는 단점이 있다.", "serdes"],
    ["DFE", "Decision Feedback Equalizer", "이미 판정한 이전 비트들이 남긴 꼬리를 계산해 빼 주는 등화기. 잡음을 키우지 않지만 판정 오류가 번질 수 있다.", "serdes"],
    ["CDR", "Clock and Data Recovery", "별도 클럭선 없이 데이터의 전이 시각에서 박자를 뽑아내 샘플링 위치를 눈 중심에 맞추는 회로.", "serdes"],
    ["지터", "Jitter", "신호 전이나 클럭의 박자가 이상적인 시각에서 들쭉날쭉 벗어나는 흔들림.", "serdes"],
    ["리드-솔로몬 부호", "Reed-Solomon code", "여러 비트를 한 심볼로 묶어 패리티 심볼을 붙이는 오류 정정 부호. 이더넷의 RS(544,514) KP4는 심볼 15개까지 고친다.", "serdes"],
    ["반사 계수", "Reflection coefficient", "임피던스가 바뀌는 지점에서 되튕기는 전압의 비율. Γ = (R − Z₀)/(R + Z₀).", "serdes"],
    ["AEC", "Active Electrical Cable", "커넥터 안에 리타이머 칩을 넣어 수동 구리 케이블(DAC)보다 멀리 가는 능동 구리 케이블.", "serdes"],
    ["UCIe", "Universal Chiplet Interconnect Express", "한 패키지 안의 칩렛끼리 넓은 병렬 배선으로 잇는 개방형 표준. 비트당 에너지가 매우 낮다.", "serdes"],
